### ISSUE TITLE
failed to run the example of in-memory analytics with the /data/ml-latest 

### ISSUE THREAD

**Issue by Jeongseob** [parsa-epfl/cloudsuite#110]
Hi,

I failed to run the SPARK ALS which is a benchmark of in-memory analytics when following the official [documentation](http://cloudsuite.ch//pages/benchmarks/inmemoryanalytics/) due to out of memory. According to the page, it looks like the ALS benchmark with the large dataset is working with 1g driver memory and 1g executor memory, but it wasn't for me. Here is output log file, [als.oom.txt](https://github.com/parsa-epfl/cloudsuite/files/1517240/als.oom.txt)

I need to have at least 2g driver memory and 2g executor memory like below. It may not be criticial, but I think it would be better if the documentation can be updated. 

```
$ docker run --rm --volumes-from data cloudsuite/in-memory-analytics /data/ml-latest /data/myratings.csv --driver-memory 2g --executor-memory 4g
```

Thanks,
Jeongseob

**Comment by ZiluTian** [comment]
Hi Jeongseob, 
Thank you for bringing this up to our attention! I am able to reproduce your error message and validate your suggested solution. We will update the instruction manual asap. 

Best, 
Zilu
