### ISSUE TITLE
hadoop-2.7.3

### ISSUE THREAD

**Issue by neo-apz** [parsa-epfl/cloudsuite#118]
Hadoop 2.7.3 tar file is not available at the following source anymore, and it causes the built to fail on Travis-CI:

`http://mirrors.gigenet.com/apache/hadoop/common/hadoop-2.7.3/hadoop-2.7.3.tar.gz`

We need to point to another source.
We may also need to update our Hadoop version (add another dockerfile with a newer version of Hadoop)

Travis-CI log file:
https://travis-ci.org/parsa-epfl/cloudsuite/jobs/340623146

**Comment by Reylak** [comment]
This mirror does no longer hosts the 2.7.3 version, but has the 2.7.4. The benchmark that uses Hadoop in CloudSuite (Data Analytics) works perfectly fine with 2.7.4, and my guess is that it works fine with any version under the same major version 2. This to say that simply updating the version in the current Dockerfile is alright, no need to create another Dockerfile for another image.

Side note: when I grepped the benchmark folder for "hadoop", I found a Hadoop version in the Spark base Dockerfile, stuck at 2.6. You may wish to update it while you're at it?

**Comment by neo-apz** [comment]
@Reylak Thanks for your interest in CloudSuite.
The issue with Hadoop is resolved now.
The Spark images download Hadoop on the fly in the compilation phase. Hence, they don't use the Hadoop image. We might change it in future though.
