### ISSUE TITLE
 bunzip2: not found

### ISSUE THREAD

**Issue by neo-apz** [parsa-epfl/cloudsuite#121]
The data-analytics benchmark is failing to build because the base image (the new Hadoop image) doesn't have bzip2 installed.

**Comment by saidulshakil** [comment]
Hi, Still it is failing to build. can you please help me.

**Comment by Hnefi** [comment]
@HKassir72 Can you please check this quickly? It should just be a matter of building in the background.

**Comment by saidulshakil** [comment]
Hi, any update regarding this?
Actually, I am doing my master's project by implementing cloudsuite benchmarks and my deadline is so near.
Any help, please.

**Comment by Hnefi** [comment]
Closing this since it was resolved in #181
