### ISSUE TITLE
Web search larger index file

### ISSUE THREAD

**Issue by yunjeongmun** [parsa-epfl/cloudsuite#133]
It's hard for me to get larger index file than 12GB index file offered by CloudSuite3.0
How can I get larger index file to run web search benchmark, or.. If you already have bigger index file, could you share for me? I think it would be 20GB~30GB size or something..

**Comment by sid1994** [comment]
Hi @yunjeongmun 

We only have a 12GB image index file.
You will need to create an image fit for your purposes.
There is good documentation available on Solr website for this.
https://lucene.apache.org/solr/guide/6_6/introduction-to-solr-indexing.html#introduction-to-solr-indexing

If you are willing to hack around Solr configurations, there also is a possibility to replicate the given index file multiple times inside Solr. However, this might require you to launch multiple instances of Solr.
