### ISSUE TITLE
web-serving benchmark issue

### ISSUE THREAD

**Issue by pradeepdogga** [parsa-epfl/cloudsuite#136]
Hi,

I am trying to run the web-serving benchmark in ubuntu, the commands I used :

docker network create net1
docker run -dt --net=net1 --name=web_server cloudsuite/web-serving:web_server /etc/bootstrap.sh mysql_server memcache_server 7
docker run -dt --net=net1 --name=memcache_server cloudsuite/web-serving:memcached_server
docker run -dt --net=net1 --name=mysql_server cloudsuite/web-serving:db_server web_server
docker run --net=net1 --name=faban_client cloudsuite/web-serving:faban_client web_server 7

This is as mentioned in http://cloudsuite.ch//pages/benchmarks/webserving/

All I see is a blank screen with no output.

Please let me know where the mistake is.

Thanks,
Pradeep.

**Comment by Hnefi** [comment]
This is a common issue if the docker containers are not able to connect to each other through the network. If you look at the `bootstrap.sh` script in the faban_client container, you will see:
`
while [ "$(curl -sSI ${WEB_SERVER_IP}:8080 | grep 'HTTP/1.1' | awk '{print $2}')" != "200" ]; do
  sleep 1
done
`
So, if the client is unable to get an HTTP 1.1 response from the web_server container, it will sleep infinitely. To solve your issues, try to launch the faban_client container **without** the bootstrap script as the entry point, and investigate the connectivity there from the command prompt.

**Comment by pradeepdogga** [comment]
I have tried connecting to the web server with curl. It says bad gateway. Upon inspecting the logs of mysql server container I found that it has stopped the mysqld service. I dont know why it is doing that.

**Comment by pradeepdogga** [comment]
The db server logs show an error during restarting the mysql server. It is successfully stopping the service but is failing to start the service again. Which is leading to the infinite wait to connect to the server. I don't understand why the service is not starting again. Any explanation for this ?

**Comment by rahulketch** [comment]
HI, 
Were you able to get it to work? 
I ran with the following commands and it works

```
docker network create test_network
docker run -dt --network=test_network  --name=mysql_server cloudsuite/web-serving:db_server web_server
docker run -dt --network=test_network --name=memcache_server cloudsuite/web-serving:memcached_server
docker run -dt --network=test_network  --name=web_server cloudsuite/web-serving:web_server /etc/bootstrap.sh
docker network inspect test_network 
```
The output after network inspect should be as followed. You can get the ip of the web_server (I have bolded it out in this example). 

>  [
>     {
>         "Name": "test_network",
>         "Id": "e34332c826f04c186b3963a3b7976c3178bbaa20e5dcc9419253d96214e8f4a9",
>         "Created": "2018-06-28T15:07:47.751361872+02:00",
>         "Scope": "local",
>         "Driver": "bridge",
>         "EnableIPv6": false,
>         "IPAM": {
>             "Driver": "default",
>             "Options": {},
>             "Config": [
>                 {
>                     "Subnet": "172.18.0.0/16",
>                     "Gateway": "172.18.0.1"
>                 }
>             ]
>         },
>         "Internal": false,
>         "Attachable": false,
>         "Ingress": false,
>         "ConfigFrom": {
>             "Network": ""
>         },
>         "ConfigOnly": false,
>         "Containers": {
>             "c6432eea26b0d8d0df03c7123939c9569c04a3efc1490dd8dbcdd1d7bf58fcef": {
>                 "Name": "web_server",
>                 "EndpointID": "1a68b5376286cba8e39eedf6df955d51ab08b2fde6a7e1c9fe3ff4cc1bcff7fc",
>                 "MacAddress": "02:42:ac:12:00:04",
>                 "IPv4Address": "**172.18.0.4**/16",
>                 "IPv6Address": ""
>             },
>             "e8774728a429ef218075193e302e242f0f887f18e5c4fa252fffa97454b9eb95": {
>                 "Name": "mysql_server",
>                 "EndpointID": "d53df882a3f8c99b6d960c197fa1ff03a5e619fe7589e61263783d2a67476697",
>                 "MacAddress": "02:42:ac:12:00:02",
>                 "IPv4Address": "172.18.0.2/16",
>                 "IPv6Address": ""
>             },
>             "ebb4f1846ff58fcd1c3fab19e77c46120b2b4825f6d1cdeb6fefce0bf8970e95": {
>                 "Name": "memcache_server",
>                 "EndpointID": "3b59638fb9187859c13794394c985db28499b4edf76d1162ea9aa1a1a0a411f2",
>                 "MacAddress": "02:42:ac:12:00:03",
>                 "IPv4Address": "172.18.0.3/16",
>                 "IPv6Address": ""
>             }
>         },
>         "Options": {},
>         "Labels": {}
>     }
> ]
> 
You can use this IP address to run the faban_client image.

`docker run --net=test_network --name=faban_client cloudsuite/web-serving:faban_client 172.18.0.4 7`

Hope that helps.

**Comment by rahulketch** [comment]
Hi,
I am closing this issue now. In case any more questions, feel free to open the issue again.

**Comment by pradeepdogga** [comment]
Hi,

Sorry for the delay, did not notice this. I tried with the commands you have given. I am still stuck with the blank screen. When I inspect logs of mysql_server, I find this : 
 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
 + sleep 1
 + :
 + mysql -uroot -proot -e status

It never ends. Please let me know what to do.

Thanks,
Pradeep.
