### ISSUE TITLE
problem when running web-search server

### ISSUE THREAD

**Issue by jinweilin7325** [parsa-epfl/cloudsuite#139]
I was trying to run web-search server on docker, I followed the instructions the cloudsuite main page. But it didn't return an  Index Node IP Address, and the program stopped at "Updating data for cloudsuite_web_search to ver 9"
can you help me with this?
the following is what what I found maybe wrong:
2018-06-27 10:06:50 (1.08 MB/s) - written to stdout [12093085208/12093085208]
Index Node IP Address: 

the program stopped running at this line:
63244 [zkCallback-2-thread-1-processing-{node_name=172.18.0.2:8983_solr}] INFO  org.apache.solr.common.cloud.ZkStateReader  [   ] ? Updating data for cloudsuite_web_search to ver 9

**Comment by rahulketch** [comment]
Hi,
Currently the IP Address is not being displayed correctly. We will be rolling a fix soon but in the meantime you can use the IP address which is displayed as the node_name.

> 63244 [zkCallback-2-thread-1-processing-{node_name=**172.18.0.2**:8983_solr}] INFO

**Comment by jinweilin7325** [comment]
Thanks!
I am also confused if I should wait on "Updating data for cloudsuite_web_search to ver 9" . nothing more has been coming up for a long time.

**Comment by rahulketch** [comment]
You don't need to wait, just run the client and it should work.
