### ISSUE TITLE
Unable to build data-caching server and client images

### ISSUE THREAD

**Issue by rahulketch** [parsa-epfl/cloudsuite#144]
When trying to build the docker images for data-caching server and client, I get the following error:

> E: Unable to locate package libevent-2.0-5
> E: Couldn't find any package by glob 'libevent-2.0-5'
> E: Couldn't find any package by regex 'libevent-2.0-5'
> The command '/bin/sh -c apt-get update && apt-get install -y libevent-2.0-5 vim --no-install-recommends 	&& rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

The issue arises because we use ubuntu:latest as the base image which has been updated to [ubuntu 18.04](https://hub.docker.com/_/ubuntu/). Using Ubuntu:16.04 works without the build errors.

**Comment by neo-apz** [comment]
#145 fixes this.
