### ISSUE TITLE
Segmentation fault in data caching loader

### ISSUE THREAD

**Issue by altostratous** [parsa-epfl/cloudsuite#174]
I previously have determined the maximum throughput and now I'm trying to run the data caching benchmark without running that step. According to the documentation I am running the following which leads to segmentation fault in the loader. (Both on dev and master)

    set -e
    cd commons/java/openjdk8
    docker build -t cloudsuite/java:openjdk8 -f Dockerfile .
    docker build -t cloudsuite/java:latest -f Dockerfile .

    cd ../openjdk7
    docker build -t cloudsuite/java:openjdk7 -f Dockerfile .

    cd ../../.. 
    # uncomment these lines if you're on dev
    # export DH_REPO="cloudsuite/memcached" 
    # export IMG_TAG="1.5.9" 
    # export DF_PATH="./commons/memcached/1.5.9"
    # docker build -t $DH_REPO:$IMG_TAG $DF_PATH

    export DH_REPO="cloudsuite/data-caching"
    export IMG_TAG="server" 
    export DF_PATH="./benchmarks/data-caching/server"
    docker build -t $DH_REPO:$IMG_TAG $DF_PATH

    export DH_REPO="cloudsuite/data-caching" 
    export IMG_TAG="client" 
    export DF_PATH="./benchmarks/data-caching/client"
    docker build -t $DH_REPO:$IMG_TAG $DF_PATH

    export DH_REPO="cloudsuite/memcached_server" 
    export IMG_TAG="latest" 
    export DF_PATH="./benchmarks/web-serving/memcached_server"
    docker build -t $DH_REPO:$IMG_TAG $DF_PATH

    docker network create caching_network || true
    docker stop $(docker ps -q) || true
    docker rm $(docker ps -aq) || true

     docker run --name dc-server1 --net caching_network -d cloudsuite/data-caching:server
     docker run --name dc-server2 --net caching_network -d cloudsuite/data-caching:server

     docker run -it --name dc-client --net caching_network cloudsuite/data-caching:client bash -c "cd /usr/src/memcached/memcached_client/; \
    echo dc-server1, 11211 > docker_servers.txt; \
    echo dc-server2, 11211 >> docker_servers.txt; \
    ./loader -a ../twitter_dataset/twitter_dataset_unscaled -o ../twitter_dataset/twitter_dataset_30x -s docker_servers.txt -w 4 -S 30 -D 4096 -j -T 1;"

    docker rm dc-client
    docker run -it --name dc-client --net caching_network cloudsuite/data-caching:client bash -c "cd /usr/src/memcached/memcached_client/; \
    echo dc-server1, 11211 > docker_servers.txt; \
    echo dc-server2, 11211 >> docker_servers.txt; \
    ./loader -a ../twitter_dataset/twitter_dataset_30x -s docker_servers.txt -g 0.8 -T 1 -c 200 -w 8 -e -r 1000;"

**Comment by altostratous** [comment]
The problem was that I was not scaling up the data set so the `../twitter_dataset/twitter_dataset_30x` parameter in the last command was not appropriate.

**Comment by swamysaranam** [comment]
Hi,

I am getting DNS error while loading the twitter_dataset in the data-analytics benchmark. Also, while running the shell script "load.sh" from the client, I was encountered with segmentation fault. Can you please help me in solving the segmentation fault error in the data-analytics benchmark.

**Comment by neo-apz** [comment]
Dear @swamysaranam,

Thanks for using CloudSuite.
Could you please create a new issue and provide more information on your setup and the actual commands you are running? Also, is your question regarding `data-analytics` or `data-caching`?

Regards,
Arash
