### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by saidulshakil** [parsa-epfl/cloudsuite#177]
Hi,

I am using Ubuntu 16.04 LTS, and for that php5 is nor working anymore. Can I use PHP7.0 for this benchmark?

**Comment by rahulketch** [comment]
Hi,

Do you mean the Ubuntu version in the host system or in the container image?

**Comment by saidulshakil** [comment]
Hi,
I mean in the Ubuntu version 16.04 LTS.
Can I deploy the benchmark in one VM, or do I have to deploy in separate VM's?
