### ISSUE TITLE
Problem with Faban_client

### ISSUE THREAD

**Issue by saidulshakil** [parsa-epfl/cloudsuite#179]
Hi,
I am using ubuntu 16.04 and tried to run web serving benchmark in one VM.
I have tried below commands after pulling the docker images.

docker run -dt --net=host --name=mysql_server cloudsuite/web-serving:db_server $ localhost
docker run -dt --net=host --name=memcache_server cloudsuite/web-serving:memcached_server
docker run -dt --net=host --name=web_server cloudsuite/web-serving:web_server /etc/bootstrap.sh $ localhost $ localhost ${MAX_PM_CHILDREN}
docker run -p 8080:8080 --net=host --name=faban_client cloudsuite/web-serving:faban_client ${WEB_SERVER_IP} ${LOAD_SCALE}

But received the below error:

WARNING: Published ports are discarded when using host network mode
curl: (6) Could not resolve host: $
curl: (6) Could not resolve host: $
curl: (6) Could not resolve host: $

I have also tried the 192.168.*.* (WEB_SERVER_IP), localhost(DATABASE_SERVER_IP) and localhost (MEMCACHED_SERVER_IP) but still receive the same issue.

Could anyone help me please.

**Comment by saidulshakil** [comment]
Also followed this - 

apt-get install bridge-utils
pkill docker
iptables -t nat -F
ifconfig docker0 down
brctl delbr docker0
service docker restart

**Comment by neo-apz** [comment]
Dear saidulshakil,

Thank you for using CloudSuite.

The error you get is very clear. It cannot resolve the address you passed, `$`.
Those `$` signs you have in your commands should not be there.

**Comment by saidulshakil** [comment]
Hi Arash Pourhabibi,

Thank you so much for your feedback.
I have followed the instruction of yours but received the below -

root@ubuntu:~# docker run -dt --net=host --name=mysql_server cloudsuite/web-serving:db_server 192.168.176.134
656635b7e1ad6159b39104851af4802b17f18871cd4b81944847aab22423f26c
root@ubuntu:~# docker run -dt --net=host --name=memcache_server cloudsuite/web-serving:memcached_server
587c961c34d6c7f9984e313c2ecd8c243410d137f246ce04af3969f68e36eab1
root@ubuntu:~# docker run -dt --net=host --name=web_server cloudsuite/web-serving:web_server /etc/bootstrap.sh localhost localhost 80
b9c84f587feca9d45961c8e4da646786ab1fcf463d8225e493587323b1f6126e
root@ubuntu:~# docker run -p 8080:8080 --net=host --name=faban_client cloudsuite/web-serving:faban_client 192.168.176.134 7
WARNING: Published ports are discarded when using host network mode

It is stuck and nothing happened. I have waited for around 20 minutes. 

Any suggestion, please

Thanks again for your help.

**Comment by saidulshakil** [comment]
Hi,
I have successfully implemented by using below lines- 
First created the network -
$ docker network create test_network

Then run the mysql_server, memcached_server and web_server
$ docker run -dt --network=test_network  --name=mysql_server cloudsuite/web-serving:db_server web_server
$ docker run -dt --network=test_network --name=memcache_server cloudsuite/web-serving:memcached_server
$ docker run -dt --network=test_network  --name=web_server cloudsuite/web-serving:web_server /etc/bootstrap.sh

Then checked the network status and find out the IP of web_server
$ docker network inspect test_network 

Then used the IP of web_server and run the Faban Client -
$ docker run --net=test_network --name=faban_client cloudsuite/web-serving:faban_client 172.18.0.4 7

In my case, it was above IP & 7 was the load scale.

Cheers 💯
