### ISSUE TITLE
Parameters reading order different from your web page

### ISSUE THREAD

**Issue by jinweilin7325** [parsa-epfl/cloudsuite#182]
In web-search/client/docker-entrypoint.sh

`#Read client parameters`
`export SCALE=$2 \`
 ` && export RAMP_UP=$3 \`
`  && export RAMP_DOWN=$4 \`
 ` && export STEADY_STATE=$5`

The parameters reading order is different from what is on your download page (http://cloudsuite.ch//pages/benchmarks/websearch/)

"the ramp-up time in seconds (90), which refers to the time required to warm up the server; the steady-state time in seconds (60), which indicates the time the benchmark is in the steady state; and the rump-down time in seconds (60), which refers to the time to wait before ending the benchmark. "

the web page suggests that steady time is the 4th parameter, and the ramp down time should be the 5th parameter.

**Comment by neo-apz** [comment]
I'm closing this for now.
Feel free to reopen it if you still have questions.
