### ISSUE TITLE
Problem with Usergen.jar of web20_benchmark

### ISSUE THREAD

**Issue by XiaowanDong** [parsa-epfl/cloudsuite#186]
Dear Cloudsuite developers,

Thank you for providing the source of Cloudsuite. In the process of setting up web serving, when I execute `cd /web20_benchmark/build && java -jar Usergen.jar http://127.0.0.1:8080 `, the following error messages show up. 

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -16
        at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:935)
        at java.lang.StringBuilder.substring(StringBuilder.java:76)
        at setup.UserGenerator.updateElggTokenAndTs(UserGenerator.java:39)
        at setup.UserGenerator.createUsers(UserGenerator.java:103)
        at setup.UserGenerator.main(UserGenerator.java:147)

Then when I am running Faban client, the following error message appears and Faban client aborts.
[java] Sep 19, 2018 2:19:46 AM com.sun.faban.driver.engine.TimeThreadWithBackground doRun
     [java] SEVERE: ElggDriverAgent[0].0: Error initializing driver object.
     [java] java.io.FileNotFoundException: /faban/users.list (No such file or directory)
     [java]     at java.io.FileInputStream.open0(Native Method)
     [java]     at java.io.FileInputStream.open(FileInputStream.java:195)
     [java]     at java.io.FileInputStream.<init>(FileInputStream.java:138)
     [java]     at java.io.FileReader.<init>(FileReader.java:72)
     [java]     at workload.driver.Web20Driver.<init>(Web20Driver.java:230)
     [java]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     [java]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
     [java]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     [java]     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
     [java]     at java.lang.Class.newInstance(Class.java:442)
     [java]     at com.sun.faban.driver.engine.TimeThreadWithBackground.doRun(TimeThreadWithBackground.java:81)
     [java]     at com.sun.faban.driver.engine.AgentThread.run(AgentThread.java:202) 
```

Could you please help me? Thank you!

Best regards,
Xiaowan

**Comment by ZiluTian** [comment]
Hi, Xiaowan, 

Is the issue still relevant? Which version of Nginx, ELGG, PHP, and Faban are you running? There are couple of things you can try: 

1. Verify Nginx is properly configured
```curl localhost:80```
should return the welcome message of Nginx "Welcome to nginx!"

2. Verify ELGG is responding properly
``` curl localhost:8080 ```
should return the login page of the ELGG. 
You can also use your browser to verify the login page is indeed loaded. 

I have noticed some PHP issues with NGINX. If you notice the login page is not properly rendered, please check your NGINX config and consider adding the following line for php configuration, inside the block ( ``` location ~ \.php$ {} ``` ) in Nginx config file at ``` /etc/nginx/sites-available/elgg ``` or ``` /etc/nginx/sites-available/default ```, depending on your setup, 

``` fastcgi_param SCRIPT_FILENAME $request_filename; ```

You should be able to see the login page of the ELGG rendered properly. 

Please also make sure the database is properly connected. You can simply remove the settings.php file from ELGG and go through the database configuration from your browser interactively. 

3. The original script for generating user list is outdated and is looking for a pattern that no longer applies for the recent version of ELGG when determining GUID. Inside the faban client container, please update 
``` src/setup/UserGenerator.java```
to file found here: 
https://github.com/ZiluTian/cloudsuite/blob/zilu-django-workload/benchmarks/web-serving/faban_client/files/web20_benchmark/src/setup/UserGenerator.java

Or you can just update the function createUsers to the function in the link provided. 

That should solve your problem. You should be able to see file users.list in faban home. 

Please let me know if you have any further question. 

Regards, 
Zilu

**Comment by XiaowanDong** [comment]
Thank you so much, Zilu! I appreciate it! Let me try your kind suggestions
and get back to you.

**Comment by ZiluTian** [comment]
Hi Xiaowan, 

Unfortunatel

**Comment by ZiluTian** [comment]
Hi Xiaowan, 

Unfortunately it is still a work in progress and I am grinding through the remaining bugs in web serving and expect to be done in the next few days. However, you should be able to see user.list generated properly. Do let me know if you encounter any other problems that I didn't see before. Thanks. 

Regards, 
Zilu

**Comment by XiaowanDong** [comment]
Thank you so much for letting me know, Zilu!

**Comment by ZiluTian** [comment]
Hi Xiaowan, 

Sorry for the delay. The web serving has being properly tested on an amd64 machine and updated. Please refer to https://cloud.docker.com/repository/docker/zilutian/web-serving for instructions on using the images. The source code is available at https://github.com/ZiluTian/cloudsuite/tree/zilu-django-workload. Please let me know if you have any questions! 

Regards, 
Zilu

**Comment by XiaowanDong** [comment]
Thank you so much, Zilu! I appreciate it!

**Comment by ZiluTian** [comment]
My pleasure! Please close the issue if it is no longer relevant after your testing. Thank you!

**Comment by neo-apz** [comment]
I'm closing this for now.
Feel free to reopen it if you have any further questions.
