### ISSUE TITLE
Init:CreateContainerError in K8s

### ISSUE THREAD

**Issue by FOSquare** [parsa-epfl/cloudsuite#187]
I deploy two medis-streaming in K8s

fyan@chronos:~$ kubectl get po -o wide
NAME                                  READY     STATUS                      RESTARTS   AGE       IP            NODE       NOMINATED NODE
streaming-client48-7bdd6686c7-27cdm   0/1       Init:CreateContainerError   0          7m        <none>        thalassa   <none>
streaming-client49-6bd4fb664d-h4pwm   0/1       Init:CreateContainerError   0          7m        10.36.128.3   phanes     <none>
streaming-server48-6ff87d749c-2zvfr   1/1       Running                     0          7m        10.40.0.1     ananke     <none>
streaming-server49-55d99fd9f5-fdjgz   1/1       Running                     0          7m        10.43.0.5     erebos     <none>

But streaming-client container shows init: createContainerError.

The logs are shown below:
fyan@chronos:~$ kubectl describe pod streaming-client49-6bd4fb664d-h4pwm
Name:               streaming-client49-6bd4fb664d-h4pwm
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               phanes/192.168.0.107
Start Time:         Wed, 19 Sep 2018 14:35:04 +0200
Labels:             app=streaming-client49
                    pod-template-hash=2680962208
Annotations:        <none>
Status:             Pending
IP:                 10.36.128.3
Controlled By:      ReplicaSet/streaming-client49-6bd4fb664d
Init Containers:
  streaming-dataset:
    Container ID:
    Image:         cloudsuite/media-streaming:dataset
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      bash
      -c
    Args:
      cp -r /videos/. /videosshare/
    State:          Waiting
      Reason:       CreateContainerError
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9t9vv (ro)
      /videosshare from data-set (rw)
Containers:
  streaming-client49:
    Container ID:
    Image:         cloudsuite/media-streaming:client
    Image ID:
    Port:          80/TCP
    Host Port:     0/TCP
    Command:
      bash
      -c
    Args:
      /root/docker-entrypoint.sh streaming-server49
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9t9vv (ro)
      /videos from data-set (rw)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data-set:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  default-token-9t9vv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-9t9vv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason          Age              From               Message
  ----     ------          ----             ----               -------
  Normal   Scheduled       6m               default-scheduler  Successfully assigned default/streaming-client49-6bd4fb664d-h4pwm to phanes
  Normal   SandboxChanged  4m               kubelet, phanes    Pod sandbox changed, it will be killed and re-created.
  Warning  Failed          1m (x2 over 4m)  kubelet, phanes    Error: context deadline exceeded
  Normal   Pulling         1m (x3 over 6m)  kubelet, phanes    pulling image "cloudsuite/media-streaming:dataset"
  Normal   Pulled          1m (x3 over 6m)  kubelet, phanes    Successfully pulled image "cloudsuite/media-streaming:dataset"

Sometimes it works good. sometimes it just show this kind of error. it seems that the program are not stalbe. or I get some configuration misteakes. Thansk a lot.

**Comment by neo-apz** [comment]
I'm closing this for now.
Feel free to reopen it if you still have questions.
