### ISSUE TITLE
cp: cannot stat '/output-stdout/*': No such file or directory

### ISSUE THREAD

**Issue by FOSquare** [parsa-epfl/cloudsuite#188]
I run media-streaming in K8s. but on some nodes, it will tell the error "cp: cannot stat '/output-stdout/*': No such file or directory". I do not know why it happenes. And on other nodes, it works very well. do you have some hints? Thanks a lot.

fyan@chronos:~$ kubectl logs streaming-client49-6bd4fb664d-5w8r5
Total clients = 4
Minimum number of sessions = 25
Maximum number of sessions = 500
Launching 4 clients on localhost
Running command httperf --hog --server streaming-server49 --videosesslog=[/videos/logs/cl-240p-10-10000-10-5-00.log,/videos/logs/cl-360p-10-4000-10-5-00.log,/videos/logs/cl-480p-10-1600-10-5-00.log,/videos/logs/cl-720p-10-800-10-5-00.log],[0.1,0.3,0.4,0.2],[localhost,localhost,localhost,localhost] --epoll --recv-buffer=524288 --port 80 --output-log=/output/result1.log --num-sessions=25 --rate=2 2>>/output/bt1.trace
Running command httperf --hog --server streaming-server49 --videosesslog=[/videos/logs/cl-240p-10-10000-10-5-00.log,/videos/logs/cl-360p-10-4000-10-5-00.log,/videos/logs/cl-480p-10-1600-10-5-00.log,/videos/logs/cl-720p-10-800-10-5-00.log],[0.1,0.3,0.4,0.2],[localhost,localhost,localhost,localhost] --epoll --recv-buffer=524288 --port 80 --output-log=/output/result2.log --num-sessions=25 --rate=2 2>>/output/bt2.trace
Running command httperf --hog --server streaming-server49 --videosesslog=[/videos/logs/cl-240p-10-10000-10-5-00.log,/videos/logs/cl-360p-10-4000-10-5-00.log,/videos/logs/cl-480p-10-1600-10-5-00.log,/videos/logs/cl-720p-10-800-10-5-00.log],[0.1,0.3,0.4,0.2],[localhost,localhost,localhost,localhost] --epoll --recv-buffer=524288 --port 80 --output-log=/output/result3.log --num-sessions=25 --rate=2 2>>/output/bt3.trace
Running command httperf --hog --server streaming-server49 --videosesslog=[/videos/logs/cl-240p-10-10000-10-5-00.log,/videos/logs/cl-360p-10-4000-10-5-00.log,/videos/logs/cl-480p-10-1600-10-5-00.log,/videos/logs/cl-720p-10-800-10-5-00.log],[0.1,0.3,0.4,0.2],[localhost,localhost,localhost,localhost] --epoll --recv-buffer=524288 --port 80 --output-log=/output/result4.log --num-sessions=25 --rate=2 2>>/output/bt4.trace
sizeof(fd_set) = 128
httperf --hog --client=0/1 --server=streaming-server49 --port=80 --uri=/ --rate=2 --send-buffer=4096 --recv-buffer=524288 --epoll --call-stats-file=
Run on hostname: streaming-client49-6bd4fb664d-5w8r5
Run at: Thu Sep 20 09:14:32 2018

hash_enter: streaming-server49 80
stat basic init: using maximum errno = 500
Benchmark stats...
0 4 5 2
1 6 10 4
1 6 6 3
1 4 1 1
1 1 0 0
1 1 0 0
1 1 0 0
1 1 0 0
1 1 0 0
1 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
Maximum connect burst length: 1

fyan@chronos:~$ kubectl describe pod streaming-client49-6bd4fb664d-5w8r5
Name:               streaming-client49-6bd4fb664d-5w8r5
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               phanes/192.168.0.107
Start Time:         Thu, 20 Sep 2018 10:55:40 +0200
Labels:             app=streaming-client49
                    pod-template-hash=2680962208
Annotations:        <none>
Status:             Running
IP:                 10.36.128.3
Controlled By:      ReplicaSet/streaming-client49-6bd4fb664d
Init Containers:
  streaming-dataset:
    Container ID:  docker://956dd6cad439eb1f0ce22a8c31245556115cb46aca80166278b9d61083c7d277
    Image:         cloudsuite/media-streaming:dataset
    Image ID:      docker-pullable://cloudsuite/media-streaming@sha256:9e42f1da86a47bafce2f521e39508705f085612d3f689ab1303522e283b29aa7
    Port:          <none>
    Host Port:     <none>
    Command:
      bash
      -c
    Args:
      cp -r /videos/. /videosshare/
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 20 Sep 2018 10:57:31 +0200
      Finished:     Thu, 20 Sep 2018 10:58:49 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9t9vv (ro)
      /videosshare from data-set (rw)
Containers:
  streaming-client49:
    Container ID:  docker://0d03821fb0244824034c1e920fddd638c078f345be12be716945947c237dc076
    Image:         cloudsuite/media-streaming:client
    Image ID:      docker-pullable://cloudsuite/media-streaming@sha256:356887c54da55ce487ccf9edb3abf8f6d6233bb8650ad195573c2b848f9dd1ee
    Port:          80/TCP
    Host Port:     0/TCP
    Command:
      bash
      -c
    Args:
      /root/docker-entrypoint.sh streaming-server49
    State:          Running
      Started:      Thu, 20 Sep 2018 11:14:32 +0200
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 20 Sep 2018 11:07:26 +0200
      Finished:     Thu, 20 Sep 2018 11:13:46 +0200
    Ready:          True
    Restart Count:  4
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9t9vv (ro)
      /videos from data-set (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  data-set:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  default-token-9t9vv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-9t9vv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  21m                default-scheduler  Successfully assigned default/streaming-client49-6bd4fb664d-5w8r5 to phanes
  Normal   Pulling    21m                kubelet, phanes    pulling image "cloudsuite/media-streaming:dataset"
  Normal   Pulled     21m                kubelet, phanes    Successfully pulled image "cloudsuite/media-streaming:dataset"
  Normal   Created    20m                kubelet, phanes    Created container
  Normal   Started    20m                kubelet, phanes    Started container
  Normal   Created    10m (x4 over 18m)  kubelet, phanes    Created container
  Normal   Started    10m (x4 over 18m)  kubelet, phanes    Started container
  Warning  BackOff    3m (x6 over 13m)   kubelet, phanes    Back-off restarting failed container
  Normal   Pulling    3m (x5 over 18m)   kubelet, phanes    pulling image "cloudsuite/media-streaming:client"
  Normal   Pulled     3m (x5 over 18m)   kubelet, phanes    Successfully pulled image "cloudsuite/media-streaming:client"
fyan@chronos:~$ kubectl logs streaming-client49-6bd4fb664d-5w8r5
Total clients = 4
Minimum number of sessions = 25
Maximum number of sessions = 500
Launching 4 clients on localhost
Running command httperf --hog --server streaming-server49 --videosesslog=[/videos/logs/cl-240p-10-10000-10-5-00.log,/videos/logs/cl-360p-10-4000-10-5-00.log,/videos/logs/cl-480p-10-1600-10-5-00.log,/videos/logs/cl-720p-10-800-10-5-00.log],[0.1,0.3,0.4,0.2],[localhost,localhost,localhost,localhost] --epoll --recv-buffer=524288 --port 80 --output-log=/output/result1.log --num-sessions=25 --rate=2 2>>/output/bt1.trace
Running command httperf --hog --server streaming-server49 --videosesslog=[/videos/logs/cl-240p-10-10000-10-5-00.log,/videos/logs/cl-360p-10-4000-10-5-00.log,/videos/logs/cl-480p-10-1600-10-5-00.log,/videos/logs/cl-720p-10-800-10-5-00.log],[0.1,0.3,0.4,0.2],[localhost,localhost,localhost,localhost] --epoll --recv-buffer=524288 --port 80 --output-log=/output/result2.log --num-sessions=25 --rate=2 2>>/output/bt2.trace
Running command httperf --hog --server streaming-server49 --videosesslog=[/videos/logs/cl-240p-10-10000-10-5-00.log,/videos/logs/cl-360p-10-4000-10-5-00.log,/videos/logs/cl-480p-10-1600-10-5-00.log,/videos/logs/cl-720p-10-800-10-5-00.log],[0.1,0.3,0.4,0.2],[localhost,localhost,localhost,localhost] --epoll --recv-buffer=524288 --port 80 --output-log=/output/result3.log --num-sessions=25 --rate=2 2>>/output/bt3.trace
Running command httperf --hog --server streaming-server49 --videosesslog=[/videos/logs/cl-240p-10-10000-10-5-00.log,/videos/logs/cl-360p-10-4000-10-5-00.log,/videos/logs/cl-480p-10-1600-10-5-00.log,/videos/logs/cl-720p-10-800-10-5-00.log],[0.1,0.3,0.4,0.2],[localhost,localhost,localhost,localhost] --epoll --recv-buffer=524288 --port 80 --output-log=/output/result4.log --num-sessions=25 --rate=2 2>>/output/bt4.trace
sizeof(fd_set) = 128
httperf --hog --client=0/1 --server=streaming-server49 --port=80 --uri=/ --rate=2 --send-buffer=4096 --recv-buffer=524288 --epoll --call-stats-file=
Run on hostname: streaming-client49-6bd4fb664d-5w8r5
Run at: Thu Sep 20 09:26:47 2018

hash_enter: streaming-server49 80
stat basic init: using maximum errno = 500
Benchmark stats...
0 4 5 2
1 6 10 4
1 5 6 3
1 4 0 1
1 0 0 0
1 0 0 0
1 0 0 0
1 0 0 0
1 0 0 0
1 0 0 0
Maximum connect burst length: 1

sizeof(fd_set) = 128
httperf --hog --client=0/1 --server=streaming-server49 --port=80 --uri=/ --rate=2 --send-buffer=4096 --recv-buffer=524288 --epoll --call-stats-file=
Run on hostname: streaming-client49-6bd4fb664d-5w8r5
Run at: Thu Sep 20 09:26:47 2018

hash_enter: streaming-server49 80
stat basic init: using maximum errno = 500
Benchmark stats...
0 4 5 2
1 6 10 4
1 5 6 3
1 3 1 1
1 0 0 0
1 0 0 0
1 0 0 0
1 0 0 0
1 0 0 0
1 0 0 0
Maximum connect burst length: 1

sizeof(fd_set) = 128
httperf --hog --client=0/1 --server=streaming-server49 --port=80 --uri=/ --rate=2 --send-buffer=4096 --recv-buffer=524288 --epoll --call-stats-file=
Run on hostname: streaming-client49-6bd4fb664d-5w8r5
Run at: Thu Sep 20 09:26:47 2018

hash_enter: streaming-server49 80
stat basic init: using maximum errno = 500
Benchmark stats...
0 4 5 2
1 6 10 3
1 6 7 3
1 4 1 1
1 1 0 0
1 1 0 0
1 1 0 0
1 1 0 0
1 1 0 0
1 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
Maximum connect burst length: 1

sizeof(fd_set) = 128
httperf --hog --client=0/1 --server=streaming-server49 --port=80 --uri=/ --rate=2 --send-buffer=4096 --recv-buffer=524288 --epoll --call-stats-file=
Run on hostname: streaming-client49-6bd4fb664d-5w8r5
Run at: Thu Sep 20 09:26:47 2018

hash_enter: streaming-server49 80
stat basic init: using maximum errno = 500
Benchmark stats...
0 4 5 2
1 6 10 4
1 6 6 3
1 4 0 1
1 1 0 1
1 1 0 1
1 1 0 1
1 1 0 1
1 1 0 1
1 1 0 1
0 1 0 1
0 1 0 1
0 1 0 1
0 1 0 1
0 1 0 1
0 1 0 1
0 1 0 1
0 1 0 1
0 1 0 1
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
0 1 0 0
Maximum connect burst length: 1

Total connections = 100
Total errors = 95
Percentage failure = 95
cp: cannot stat '/output-stdout/*': No such file or directory
Benchmark failed for 25 sessions
Minimum Limit for number of sessions too high.
Requests: 169
Replies: 74
Reply rate: .12
Reply time: 80.45
Net I/O: 752.8
httperf: maximum number of open descriptors = 0
httperf: maximum number of open descriptors = 0
httperf: maximum number of open descriptors = 0
httperf: maximum number of open descriptors = 0

**Comment by ZiluTian** [comment]
Hi, 
I did notice similar error for "httperf: maximum number of open descriptors = 0". Did you check to make sure the port 80 is not used on these other nodes? It might be that the port is already in use. Please make sure client actually receives response from the server. 

Regards, 
Zilu

**Comment by ZiluTian** [comment]
Hi, 

The benchmark is working properly. Internally it does binary search between the min and max session count, as the benchmark suggested, "Minimum Limit for number of sessions too high." Please try to lower the min number of session accordingly. 

Regards, 
Zilu

**Comment by neo-apz** [comment]
I'm closing this for now.
Feel free to reopen it if you have any further questions.
