### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by meta1360** [parsa-epfl/cloudsuite#191]
When I run 
docker pull cloudsuite/hadoop

I will get 
FATA[0000] Post http:///var/run/docker.sock/v1.18/images/create?fromImage=cloudsuite%2Fhadoop%3Alatest: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS? 

Would you please tell me how to fix it.

**Comment by neo-apz** [comment]
This is apparently due to your permission configuration.
I believe you can resolve this by either using ```sudo``` when executing the command or adding your user to the docker group.
