### ISSUE TITLE
curl: (7) Failed to connect to 192.168.122.13 port 8080: Connection refused

### ISSUE THREAD

**Issue by tonys24** [parsa-epfl/cloudsuite#192]
Hi,
I follow the instruction of the webserving benchmarks. But the following error comes when the client is on. Could anyone tell me how to fix that?

sudo docker run --net=host --name=faban_client cloudsuite/web-serving:faban_client 192.168.122.13  7
curl: (7) Failed to connect to 192.168.122.13 port 8080: Connection refused
Could not perform HTTP 200 GET from: 192.168.122.13:8080
curl: (7) Failed to connect to 192.168.122.13 port 8080: Connection refused
Could not perform HTTP 200 GET from: 192.168.122.13:8080
curl: (7) Failed to connect to 192.168.122.13 port 8080: Connection refused
Could not perform HTTP 200 GET from: 192.168.122.13:8080
curl: (7) Failed to connect to 192.168.122.13 port 8080: Connection refused
Could not perform HTTP 200 GET from: 192.168.122.13:8080

**Comment by tonys24** [comment]
I tried this:

Connecting to 192.168.122.13:8080... failed: Connection refused.

**Comment by tonys24** [comment]
I have solved my problem. The port 8080 is conflicted. It worked when following the cloudsuite instructions. 

BUILD SUCCESSFUL
Total time: 1 minute 2 seconds
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../xslt/summary_report.xsl"?>
<benchResults>
    <benchSummary name="Elgg benchmark" version="1.0">
        <runId>1</runId>
        <startTime>Sun Nov 25 16:02:46 GMT 2018</startTime>
        <endTime>Sun Nov 25 16:03:36 GMT 2018</endTime>
        <metric unit="ops/sec">3.300</metric>
        <passed>false</passed>
    </benchSummary>
    <driverSummary name="ElggDriver">
        <metric unit="ops/sec">3.300</metric>
        <startTime>Sun Nov 25 16:02:46 GMT 2018</startTime>
        <endTime>Sun Nov 25 16:03:36 GMT 2018</endTime>
        <totalOps unit="operations">99</totalOps>
        <users>7</users>
        <rtXtps>5.3861</rtXtps>
        <passed>false</passed>
        <mix allowedDeviation="0.0200">
            <operation name="BrowsetoElgg">
                <successes>0</successes>
                <failures>0</failures>
                <mix>0.0000</mix>
                <requiredMix>0.0103</requiredMix>
                <passed>true</passed>
            </operation>
            <operation name="DoLogin">
                <successes>1</successes>
                <failures>0</failures>
                <mix>0.0128</mix>
                <requiredMix>0.0103</requiredMix>
                <passed>true</passed>
            </operation>
            <operation name="PostSelfWall">
                <successes>21</successes>
                <failures>0</failures>
                <mix>0.2692</mix>
                <requiredMix>0.3090</requiredMix>
                <passed>false</passed>
            </operation>
            <operation name="SendChatMessage">
                <successes>51</successes>
                <failures>0</failures>
                <mix>0.6538</mix>
                <requiredMix>0.5664</requiredMix>
                <passed>false</passed>
            </operation>
            <operation name="AddFriend">
                <successes>5</successes>
                <failures>0</failures>
                <mix>0.0641</mix>
                <requiredMix>0.0927</requiredMix>
                <passed>false</passed>
            </operation>
            <operation name="Register">
                <successes>0</successes>
                <failures>0</failures>
                <mix>0.0000</mix>
                <requiredMix>0.0010</requiredMix>
                <passed>true</passed>
            </operation>
            <operation name="Logout">
                <successes>0</successes>
                <failures>0</failures>
                <mix>0.0000</mix>
                <requiredMix>0.0103</requiredMix>
                <passed>true</passed>
            </operation>
            <operation name="UpdateActivity &amp;">
                <successes>9</successes>
                <failures>0</failures>
                <mix>0.4286</mix>
                <requiredMix>0.5000</requiredMix>
                <passed>false</passed>
            </operation>
            <operation name="ReceiveChatMessage &amp;">
                <successes>12</successes>
                <failures>0</failures>
                <mix>0.5714</mix>
                <requiredMix>0.5000</requiredMix>
                <passed>false</passed>
            </operation>
        </mix>
        <responseTimes unit="milliseconds">
            <operation name="BrowsetoElgg">
                <avg/>
                <max/>
                <sd/>
                <p90th/>
                <passed/>
                <p99th/>
            </operation>
            <operation name="DoLogin">
                <avg>423.386</avg>
                <max>423.386</max>
                <sd>0.000</sd>
                <percentile nth="95" suffix="th" limit="500.000">10.000</percentile>
                <percentile nth="99" suffix="th" limit="1000.000">10.000</percentile>
                <percentile nth="99.9" suffix="th" limit="2000.000">10.000</percentile>
                <passed>true</passed>
            </operation>
            <operation name="PostSelfWall">
                <avg>153.116</avg>
                <max>174.292</max>
                <sd>11.688</sd>
                <percentile nth="95" suffix="th" limit="500.000">170.000</percentile>
                <percentile nth="99" suffix="th" limit="750.000">170.000</percentile>
                <percentile nth="99.9" suffix="th" limit="1000.000">170.000</percentile>
                <passed>true</passed>
            </operation>
            <operation name="SendChatMessage">
                <avg>277.495</avg>
                <max>5100.187</max>
                <sd>973.927</sd>
                <percentile nth="95" suffix="th" limit="500.000">100.000</percentile>
                <percentile nth="99" suffix="th" limit="750.000">5100.000</percentile>
                <percentile nth="99.9" suffix="th" limit="1000.000">5100.000</percentile>
                <passed>false</passed>
            </operation>
            <operation name="AddFriend">
                <avg>102.029</avg>
                <max>109.636</max>
                <sd>2.447</sd>
                <percentile nth="95" suffix="th" limit="500.000">110.000</percentile>
                <percentile nth="99" suffix="th" limit="750.000">110.000</percentile>
                <percentile nth="99.9" suffix="th" limit="1000.000">110.000</percentile>
                <passed>true</passed>
            </operation>
            <operation name="Register">
                <avg/>
                <max/>
                <sd/>
                <p90th/>
                <passed/>
                <p99th/>
            </operation>
            <operation name="Logout">
                <avg/>
                <max/>
                <sd/>
                <p90th/>
                <passed/>
                <p99th/>
            </operation>
            <operation name="UpdateActivity &amp;">
                <avg>92.792</avg>
                <max>138.920</max>
                <sd>39.484</sd>
                <percentile nth="95" suffix="th" limit="500.000">120.000</percentile>
                <percentile nth="99" suffix="th" limit="750.000">120.000</percentile>
                <percentile nth="99.9" suffix="th" limit="1000.000">120.000</percentile>
                <passed>true</passed>
            </operation>
            <operation name="ReceiveChatMessage &amp;">
                <avg>503.437</avg>
                <max>5092.379</max>
                <sd>1383.681</sd>
                <percentile nth="95" suffix="th" limit="500.000">110.000</percentile>
                <percentile nth="99" suffix="th" limit="750.000">110.000</percentile>
                <percentile nth="99.9" suffix="th" limit="1000.000">110.000</percentile>
                <passed>true</passed>
            </operation>
        </responseTimes>
        <delayTimes>
            <operation name="BrowsetoElgg" type="thinkTime">
                <targetedAvg>9.000</targetedAvg>
                <actualAvg>8.999</actualAvg>
                <min>1.999</min>
                <max>10.000</max>
                <passed>true</passed>
            </operation>
            <operation name="DoLogin" type="thinkTime">
                <targetedAvg>6.308</targetedAvg>
                <actualAvg>6.545</actualAvg>
                <min>1.999</min>
                <max>10.000</max>
                <passed>true</passed>
            </operation>
            <operation name="PostSelfWall" type="thinkTime">
                <targetedAvg>2.000</targetedAvg>
                <actualAvg>1.999</actualAvg>
                <min>1.999</min>
                <max>1.999</max>
                <passed>true</passed>
            </operation>
            <operation name="SendChatMessage" type="thinkTime">
                <targetedAvg>2.000</targetedAvg>
                <actualAvg>1.999</actualAvg>
                <min>1.999</min>
                <max>1.999</max>
                <passed>true</passed>
            </operation>
            <operation name="AddFriend" type="thinkTime">
                <targetedAvg>2.000</targetedAvg>
                <actualAvg>1.999</actualAvg>
                <min>1.999</min>
                <max>1.999</max>
                <passed>true</passed>
            </operation>
            <operation name="Register" type="thinkTime">
                <targetedAvg/>
                <actualAvg/>
                <min/>
                <max/>
                <passed/>
            </operation>
            <operation name="Logout" type="thinkTime">
                <targetedAvg/>
                <actualAvg/>
                <min/>
                <max/>
                <passed/>
            </operation>
            <operation name="UpdateActivity &amp;" type="cycleTime">
                <targetedAvg/>
                <actualAvg/>
                <min/>
                <max/>
                <passed/>
            </operation>
            <operation name="ReceiveChatMessage &amp;" type="cycleTime">
                <targetedAvg/>
                <actualAvg/>
                <min/>
                <max/>
                <passed/>
            </operation>
        </delayTimes>
        <customStats name="Miscellaneous Statistics">
            <stat>
                <description>Number of times home page was actually attempted to be accessed.</description>
                <result>8</result>
                <passed>true</passed>
            </stat>
            <stat>
                <description>Number of times login was actually attempted.</description>
                <result>8</result>
                <passed>true</passed>
            </stat>
            <stat>
                <description>Number of times posting on wall was actually attempted.</description>
                <result>32</result>
                <passed>true</passed>
            </stat>
            <stat>
                <description>Number of times update activity was actually attempted.</description>
                <result>12</result>
                <passed>true</passed>
            </stat>
            <stat>
                <description>Number of times add friends was actually attempted.</description>
                <result>8</result>
                <passed>true</passed>
            </stat>
            <stat>
                <description>Number of times send message was actually attempted.</description>
                <result>69</result>
                <passed>true</passed>
            </stat>
            <stat>
                <description>Number of times receive message was actually attempted.</description>
                <result>15</result>
                <passed>true</passed>
            </stat>
            <stat>
                <description>Number of times logout was actually attempted.</description>
                <result>1</result>
                <passed>true</passed>
            </stat>
            <stat>
                <description>Number of times register was actually attempted.</description>
                <result>0</result>
                <passed>true</passed>
            </stat>
        </customStats>
    </driverSummary>
</benchResults>

**Comment by Hnefi** [comment]
Hi, since you resolved this I'll close the issue.
