### ISSUE TITLE
How to execute media streaming on different hosts?

### ISSUE THREAD

**Issue by kevinsuo** [parsa-epfl/cloudsuite#193]
In the media streaming benchmark instructions, the clients run this:

$ docker run -t --name=streaming_client -v /path/to/output:/output --volumes-from streaming_dataset --net streaming_network cloudsuite/media-streaming:client streaming_server

However, the streaming_dataset is at the server side. The instruction only works for containers on the same host. Thanks.

**Comment by rkgithubs** [comment]
thanks, I'll take a look at the overlay networks. I was already running server and client in two different containers. Seems like your response is in line with my approach.
