### ISSUE TITLE
Spark Issue

### ISSUE THREAD

**Issue by rkgithubs** [parsa-epfl/cloudsuite#195]
I'm starting to deploy cloudsuite on a single instance. I notice that some of the commands need spark to be available on the system. Which spark version should i download, the cloudsuite page doesn't talk about it.

**Comment by neo-apz** [comment]
None of them CloudSuite benchmarks need you to have Spark installed on your system. Those that depend on Spark will have it installed using Docker. So there is no need to install Spark manually on your system.
