### ISSUE TITLE
How to limit cloud Suite to number of cores (CPUs) 

### ISSUE THREAD

**Issue by rkgithubs** [parsa-epfl/cloudsuite#197]
I'm able to run graph-analytics and in-memory analytics on single machines. I think rest of the tests need multiple servers, clients etc. Is there a way to limit the test(s) to use only few number of cores/cpus on the server instead of all of them. Is there a setting inside docker image or is it a spark setting?

**Comment by sid1994** [comment]
Hi

You can limit the number of cores a docker instance can use.
This is similar to pinning processes on a set of cores.
Please check the following:
https://docs.docker.com/config/containers/resource_constraints/#--memory-swappiness-details

Also, please do close the issue once your question is resolved.
Thank you.

**Comment by rkgithubs** [comment]
thanks!
