### ISSUE TITLE
Data Analytics test: MAHOUT path not found 

### ISSUE THREAD

**Issue by rkgithubs** [parsa-epfl/cloudsuite#199]
Hi,

this might be more related to MAHOUT installation. I have tried to install mahout a few times by 'mvn install' on the source zip e.g. mahout-distribution-x.x-src.zip. Installation pauses on some broken pom file. 

when i tried to run the Data Analytics test- i get the following error and bunch of failures followed by stack trace of the failed locations. I did try to set up export MAHOUT_LOCAL="TRUE" 

MAHOUT_LOCAL is not set; adding HADOOP_CONF_DIR to classpath.

Running on hadoop, using /opt/hadoop-2.7.4/bin/hadoop and HADOOP_CONF_DIR=/opt/hadoop-2.7.4/etc/hadoop
MAHOUT-JOB: /opt/mahout-0.12.2/mahout-examples-0.12.2-job.jar
18/12/17 15:44:11 WARN MahoutDriver: No testnb.props found on classpath, will use command-line arguments only
18/12/17 15:44:11 INFO AbstractJob: Command line arguments: {--endPhase=[2147483647], --input=[/user/root/testing], --labelIndex=[/user/root/labelindex], --model=[/user/root/model], --output=[/user/root/output], --overwrite=null, --runSequential=null, --startPhase=[0], --tempDir=[temp]}
Exception in thread "main" java.io.FileNotFoundException: File does not exist: /user/root/model/naiveBayesModel.bin
	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:71)
	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:61)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocationsInt(FSNamesystem.java:1836)

**Comment by ZiluTian** [comment]
Hi, 
Please refer to our latest image which has Mahout properly installed: 
https://cloud.docker.com/u/zilutian/repository/docker/zilutian/data-analytics

Regards, 
Zilu

**Comment by apptimise** [comment]
This is still a problem and not resolved. Any updates?

**Comment by ZiluTian** [comment]
Hi, 
Did you use the recent image as specified in the path above? 

Regards, 
Zilu

**Comment by apptimise** [comment]
Hi. Ok, it seems that the url is broken. I think you mean to follow the steps specified here?
https://hub.docker.com/r/zilutian/data-analytics
I'll give it another go. Thanks!

**Comment by neo-apz** [comment]
I'm closing this for now.
Feel free to reopen it if you have any further questions.
