### ISSUE TITLE
data-serving benchmark is old

### ISSUE THREAD

**Issue by sarsanaee** [parsa-epfl/cloudsuite#202]
Hi,

I tried to install a couple of benchmarks like `data-serving`, and they look pretty old. Like the Cassandra for the `data-serving` benchmark is `2.1.12` and the based image is `ubuntu 14.04` while the current Cassandra release is `3.11.3` and ubuntu 18.04 based image should be used I guess. Concerning this particular benchmark, we cannot use `setup_tables.txt` script for newer versions of Cassandra and it has some errors. Isn't it possible to reconfigure this benchmark with newer packages and system base images?

Thanks,
Alireza

**Comment by ZiluTian** [comment]
Hi, 
Please take a look at the dev (for x86) or dev_arm (for aarch64) branch. Those two contain updated packages. 

Regards, 
Zilu

**Comment by sarsanaee** [comment]
Hi @ZiluTian 

Thank you for the message.

Also, the images at Docker Hub are a bit old, you might update them!

**Comment by ZiluTian** [comment]
Hi, 

We are in the process of updating workloads. Sorry for any inconvenience. The recent images at Docker Hub for ARM can be found at zilutian/data-serving-client-aarch64 and zilutian/data-serving-server-aarch64. If you have any trouble building images for x86, please let us know. 

Regards, 
Zilu

**Comment by sarsanaee** [comment]
Thank you for sharing updated images.

I'm working on integrating Pin with all these benchmarks so I'd prefer to have the updated images rather than the old one. For now, I'm updating one by one on my own. I definitely take a look at the images you pointed out.

Thanks
