### ISSUE TITLE
In-memory benchmark doesn't scale- Executor locks

### ISSUE THREAD

**Issue by rkgithubs** [parsa-epfl/cloudsuite#203]
In my experience, in-memory analytics test doesn't scale past two containers- running 6 cores inside each containers. Seeing executor locks messages while running more than two docker containers x 6 cores/each. Have any of these tests known to scale across 20-28 cores in multiple docker setups.

**Comment by ZiluTian** [comment]
Hi, thanks for letting us know. Have you checked if these 6 cores are physically isolated? For SMT-enabled or hyperthreaded machines, it is recommended to ping clients and servers to physically separated cores to reduce the thread contention. Please let us know if you continue having trouble.

**Comment by ZiluTian** [comment]
Hi, 
I have recently tested the in-memory analytics on a 24 core machine with 3 workers and 1 master each assigned with 6 cores, and I am unable to reproduce your issue. (The latest image for in memory analytics can be found here: https://cloud.docker.com/u/zilutian/repository/docker/zilutian/in-memory-analytics) Please make sure you properly isolate your core assignment when using --cpuset-cpus. Please reopen the issue with supplementary details if you continue experiencing similar problems. Thank you. 

Regards, 
Zilu
