### ISSUE TITLE
Hello, I have 1 server and 2 clients, all of them on different X86 servers. And connection reset by peer error is occurring when i run the benchmarks. 

### ISSUE THREAD

**Issue by aayush29071996** [parsa-epfl/cloudsuite#219]
I have created a single server on 1 of the X-86 with ipaddress - 192.168.4.4 and connected the clients through by creating a docker MACVLAN and attach it to the ethernet port of the systems. But when I create the clients on the other 2 X-86 servers in individual docker VM on the same MACVLAN network, but both of the benchmarks are not working together, one works and the other gives an error of "Connection reset by peer error". So how do i proceed with my testing in this kind of environment? Thanks a lot for the help.

**Comment by ZiluTian** [comment]
Hi, just to make sure I understand the question clearly, so you are trying to connect multiple clients to a single server and only one of the clients is connected while the rest resulting in "connection reset by peer"? Have you looked at the port assignment for the clients? To be able to reproduce the issue, I need more information regarding the specific benchmark you are experimenting with and your config.
