### ISSUE TITLE
DNS error while loading the twitter dataset in data-caching

### ISSUE THREAD

**Issue by swamysaranam** [parsa-epfl/cloudsuite#221]
Hi,

While running the foloowing comand in the client console, I was encountered with a DNS error.
./loader -a ../twitter_dataset/twitter_dataset_unscaled -o ../twitter_dataset/twitter_dataset_30x -s docker_servers.txt -w 4 -S 30 -D 4096 -j -T 1

Can you help me solve this problem?

Thanks,
swamy.

**Comment by neo-apz** [comment]
Can you provide more details on the error you get? What does it say exactly?
Also, could you provide the content of `docker_servers.txt` and tell us more about your setup? e.g., how you connected your nodes? are you using docker? how many nodes do you have? etc.

**Comment by swamysaranam** [comment]
Hi Neo,

I haven't run all the four dc-servers before starting the client. Hence, DNS error occurred. After starting all 4 servers,  I am able to download the twitter dataset. 

Thank you for the quick response.
Swamy.
