### ISSUE TITLE
faban_client the mix is wrong

### ISSUE THREAD

**Issue by marqsbla** [parsa-epfl/cloudsuite#222]
![ops](https://user-images.githubusercontent.com/35571600/57787060-01485380-7735-11e9-9c14-7e3908fa8cd5.png)
Hi,
The actual mix is wrong for all requests (percentage of mix should be 100% in the whole row). I ran the same benchmark in February last year and everything was ok for me. I quite urgently need to redo this benchmarks on new hardware and I cannot due to this error. Do you know what can cause it? 
For me it would be best if somehow I could use the faban_client from Feb 01 2018. I can't find the image though. Is there a chance you have it somewhere?
Regards,
Marek

**Comment by marqsbla** [comment]
ok, I recreated the image from the sources, but problem with the distribution of requests is still there, so I leave the issue open.

**Comment by ZiluTian** [comment]
Hi Marek, 
You can easily configure the distribution of requests in  /faban_client/files/web20_benchmark/src/workload/driver/Web20Driver.java  Please let me know if it helps. 

Regards, 
Zilu
