### ISSUE TITLE
Getting trace for cloudsuite benchmarks by Intel Pin

### ISSUE THREAD

**Issue by meta1360** [parsa-epfl/cloudsuite#223]
Hello,
How to generate a memory trace of Cloudsuite benchmarks by using Intel Pin.  If there is any other way to create the memory trace of these benchmarks, I appreciate it if you share it with me. 

Thanks

**Comment by ZiluTian** [comment]
Hello, 

Did you try to get the trace from the host or from inside the container? One way to go about it is to share the Pin folder with the container through -v option and to start the container with --privileged mode, then while the container is running, using `docker exec -it /bin/bash` to get inside the container. From the host side, you may need to modify ptrace_scope `echo 0 > /proc/sys/kernel/yama/ptrace_scope` Be aware that the pid inside container is different from that of the host. Once you are inside the container, you can proceed normally using `pin -pid ...` with the pid inside container, and you should be able to attach to the process. Please let me know if it helps or if you have any followup questions. 

Regard, 
Zilu

**Comment by meta1360** [comment]
Thank you Zilu for your reply,
I want to get a trace from the container. For example, when I want to run "data caching", where should I share the Pin folder with the container? in this command?
 $ docker run --name dc-server1 --net caching_network -d cloudsuite/data-caching:server -t 4 -m 4096 -n 550 -v path_of_intel_PIN ? 
Then can I access to pin folder when I am in the container? 
I did that but I still do not have access to the pin folder when I am in the container
memcache@d6d20a833447:/usr/src/memcached/memcached_client$

thanks for your help.

**Comment by ZiluTian** [comment]
Hi,

Please consult https://docs.docker.com/engine/reference/commandline/run/ this documentation page for more detailed explanation regarding options for `docker run`. For -v, please use path_of_intel_PIN_on_local_machine:path_of_Intel_PIN_inside_container and make sure both paths are absolute paths.


Regards,
Zilu


On 20 Oct 2019, at 05:57, meta1360 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you Zilu for your reply,
I want to get a trace from the container. For example, when I want to run "data caching", where should I share the Pin folder with the container? in this command?
$ docker run --name dc-server1 --net caching_network -d cloudsuite/data-caching:server -t 4 -m 4096 -n 550 -v path_of_intel_PIN ?
Then can I access to pin folder when I am in the container?
I did that but I still do not have access to the pin folder when I am in the container
memcache@d6d20a833447:/usr/src/memcached/memcached_client$

thanks for your help.

**Comment by meta1360** [comment]
Hi,
when I create a master and some slaves according to 
https://github.com/parsa-epfl/cloudsuite/blob/master/docs/benchmarks/data-analytics.md
for data-analytics benchmark, it is mentioned that to run the benchmark, I have to run this command:
docker exec master benchmark

Am I correct if I say by running this command I am able to run map-reduce on these master-slaves? and to get the trace by using intel Pin, I have to run 

$PATH/pin -t $PATH/source/tools/SimpleExamples/obj-intel64/dcache.so -- docker exec master benchmark

Is that the correct way of getting all memory accesses of this benchmark?

thanks

**Comment by ZiluTian** [comment]
Hi,

To run the benchmark as is, i.e. from outside the container, you use command
```
docker exec master benchmark
```
You can check the log of both master and slave nodes to ensure that the MapReduce is properly carried out.

For collecting Pin trace, you may need to run the command from inside container to get around some permission issues. To do this,
after launching master/slave, (BTW, slave is the one who actually does the work, so you may want to measure the trace for Slave instead),
since you have already mounted the PIN folder, before starting the execution of benchmark, to collect the trace of the master, run
```
docker exec -it master /bin/bash
```
Now the interactive shell prompt is for Master container. Simply run (notice how docker exec is removed, since we are inside the container now)
```

$PATH/pin -t $PATH/source/tools/SimpleExamples/obj-intel64/dcache.so — benchmark

```
where ```benchmark``` is an alias for ```/root/benchmark.sh```


Regards,
Zilu

On 27 Oct 2019, at 02:08, meta1360 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
when I create a master and some slaves according to
https://github.com/parsa-epfl/cloudsuite/blob/master/docs/benchmarks/data-analytics.md
for data-analytics benchmark, it is mentioned that to run the benchmark, I have to run this command:
docker exec master benchmark

Am I correct if I say by running this command I am able to run map-reduce on these master-slaves? and to get the trace by using intel Pin, I have to run

$PATH/pin -t $PATH/source/tools/SimpleExamples/obj-intel64/dcache.so -- docker exec master benchmark

Is that the correct way of getting all memory accesses of this benchmark?

thanks

**Comment by neo-apz** [comment]
I'm closing this for now.
Feel free to reopen it if you have any further questions.

**Comment by sarabjeetsingh007** [comment]
My issue is that as soon as I attach pin to the process on slave machine, the process instantly terminates. Can't seem to understand why that it. I have attached the log that prints out on master as the slave crashes.
Is there a simpler way to instrument/profile the benchmarks?
I was trying to attach Pin to instrument Data Analytics workload. My methodology is following:
1. I follow the guidelines from the guide page.

1. I install Pintool within the docker containers of master and slaves    

1. All docker containers have privileged flag and can attach to a running process (kernel.yama.ptrace_scope=0). I have tested out a simple pintool with sample code.

1. Initiate the MapReduce workload by running master and slaves

1. Meanwhile, go inside one of the slave docker container. Look for the pid of working process. Attach pin to it.

`
ob: map 75% reduce 0%
20/09/25 08:04:59 INFO Job: Task Id : attempt_1601019528768_0018_m_000000_0, Status : FAILED
[2020-09-25 08:04:58.737]Container [pid=3562,containerID=container_1601019528768_0018_01_000004] is running beyond virtual memory limits. Current usage: 619.7 MB of 2 GB physical memory used; 4.2 GB of 4.2 GB virtual memory used. Killing container.
Dump of the process-tree for container_1601019528768_0018_01_000004 :
|- PID PPID PGRPID SESSID CMD_NAME USER_MODE_TIME(MILLIS) SYSTEM_TIME(MILLIS) VMEM_USAGE(BYTES) RSSMEM_USAGE(PAGES) FULL_CMD_LINE
|- 3566 3562 3562 3562 (java) 2594 50 4555460608 157983 /usr/lib/jvm/java-11-openjdk-amd64/bin/java -Djava.net.preferIPv4Stack=true -Dhadoop.metrics.log.level=WARN -Xmx1848m -Djava.io.tmpdir=/tmp/hadoop-root/nm-local-dir/usercache/root/appcache/application_1601019528768_0018/container_1601019528768_0018_01_000004/tmp -Dlog4j.configuration=container-log4j.properties -Dyarn.app.container.log.dir=/opt/hadoop-2.9.2/logs/userlogs/application_1601019528768_0018/container_1601019528768_0018_01_000004 -Dyarn.app.container.log.filesize=0 -Dhadoop.root.logger=INFO,CLA -Dhadoop.root.logfile=syslog org.apache.hadoop.mapred.YarnChild 172.18.0.5 42741 attempt_1601019528768_0018_m_000000_0 4
|- 3562 3560 3562 3562 (bash) 0 0 3743744 668 /bin/bash -c /usr/lib/jvm/java-11-openjdk-amd64/bin/java -Djava.net.preferIPv4Stack=true -Dhadoop.metrics.log.level=WARN -Xmx1848m -Djava.io.tmpdir=/tmp/hadoop-root/nm-local-dir/usercache/root/appcache/application_1601019528768_0018/container_1601019528768_0018_01_000004/tmp -Dlog4j.configuration=container-log4j.properties -Dyarn.app.container.log.dir=/opt/hadoop-2.9.2/logs/userlogs/application_1601019528768_0018/container_1601019528768_0018_01_000004 -Dyarn.app.container.log.filesize=0 -Dhadoop.root.logger=INFO,CLA -Dhadoop.root.logfile=syslog org.apache.hadoop.mapred.YarnChild 172.18.0.5 42741 attempt_1601019528768_0018_m_000000_0 4 1>/opt/hadoop-2.9.2/logs/userlogs/application_1601019528768_0018/container_1601019528768_0018_01_000004/stdout 2>/opt/hadoop-2.9.2/logs/userlogs/application_1601019528768_0018/container_1601019528768_0018_01_000004/stderr

[2020-09-25 08:04:58.743]Container killed on request. Exit code is 143
[2020-09-25 08:04:58.753]Container exited with a non-zero exit code 143.
`

I checked out the memory and disk usage of the containers. They seem to be well below the bounds.

**Comment by Amit-P89** [comment]
Hi, execution of many of the benchmarks have to be started by the client side or by the master , where as the work will be done by the server or the slaves.

How can I attach pin with server and slaves to trace their memory accesses using my Pintool. I had already added pin directory to master or server. What should I do next to start the pin on them through client or master.
