### ISSUE TITLE
Data Caching output

### ISSUE THREAD

**Issue by Anjali05** [parsa-epfl/cloudsuite#232]
@ZiluTian I was running the data caching workload. In the doc it says the metric I should be looking at is maximum throughput. I ran the following command to get the maximum throughput:
`./loader -a ../twitter_dataset/twitter_dataset_30x -s docker_servers.txt -g 0.8 -T 1 -c 200 -w 8`

I am confused as when to stop the workload as it keeps printing rps and never stops. Do I need to stop it explicitly? And how will I know that it has reached the max throughput?

Thanks

**Comment by neo-apz** [comment]
Hi,

The option ` -T 1` tells the loader to print the status at every second. You can change that to only print the status after a longer duration of time and get the average completed requests over a longer period of time.

By default, the loader runs forever and you have to stop it manually (Ctrl-C). You can use the `-t arg` option to set a limit, for instance `-t 120` tells the loader to run for 120 seconds.

For more information on the available options run `./loader -h`.

**Comment by ZiluTian** [comment]
Hi, 

Just to add to it, one way to decide how long you would like to run is to look at the latency metric. The latency measurements are in milliseconds, and you can measure/observe how long it takes to reach your desired latency goal and then use it as your argument.  

Regards, 
Zilu
