### ISSUE TITLE
data analytics rerun error

### ISSUE THREAD

**Issue by yimjinkyu1** [parsa-epfl/cloudsuite#233]
data analytics rerun error.
java.net.ConnectionException: connection refused.
I think it is because of hadoop safe mode on.
Could you help me for solving this problem?

**Comment by ZiluTian** [comment]
Hello, 
Can you please check what version of Hadoop is it? It is likely due to an outdated version. We can currently in the process of updating it. In the mean time, you can check out the image at https://hub.docker.com/r/zilutian/data-analytics which includes all the updates. 

Regards, 
Zilu

**Comment by yimjinkyu1** [comment]
I also tested docker of zilitian version. But It failed too. Because of hadoop connection refused.

**Comment by neo-apz** [comment]
@yimjinkyu1 Can you please provide more information on how you are running things? Also please explain your execution environment.
