### ISSUE TITLE
Web Serving Session Type

### ISSUE THREAD

**Issue by aadewojo** [parsa-epfl/cloudsuite#234]
Hi,

Could you please tell me the type of session using in the web serving mode of cloud suite?

Thanks.

**Comment by ZiluTian** [comment]
Hi, 

You can find it in file 
web-serving/faban_client/files/web20_benchmark/src/workload/driver/Web20Driver.java. 
There is also a matrix that defines the ratio of each type. 

Regards, 
Zilu

**Comment by aadewojo** [comment]
Hi,
Thanks for the response. I think I didn't caption my question well. I was hoping to know if it does a stateless or stateful session when running?

**Comment by ZiluTian** [comment]
Hi, 
I am not an expert in web development, but I will try to help. According to the definition here https://nordicapis.com/defining-stateful-vs-stateless-web-services/, the current setup is stateful.  https://github.com/ZiluTian/cloudsuite/blob/zilu-django-workload/benchmarks/web-serving/faban_client/files/web20_benchmark/src/workload/driver/Web20Driver.java#L374 

Regards, 
Zilu
