### ISSUE TITLE
A potential bug in the data-caching benchmark and a question about the dataset

### ISSUE THREAD

**Issue by lukeluocn** [parsa-epfl/cloudsuite#236]
Hello, recently I'm working with the data-caching benchmark and I'm curious about how the data-caching client uses the twitter-dataset to sample packet sizes. However, I am confused with the dataset and have found a potential bug in generating random values.

### Question: How to interpret the twitter-dataset?

At first, I thought the dataset contains a CDF of packet sizes as the source code of the data-caching client uses the variable name `cdfValue`. However, the plot of the data points suggests that it does not represent a CDF, nor a PMF:

![image](https://user-images.githubusercontent.com/14174441/74944754-73bb3200-5431-11ea-8b41-963ad934aefc.png)

Nonetheless, I tried to figure out the underlying CDF that the client actually samples from and got the function below:

![image](https://user-images.githubusercontent.com/14174441/74944966-e0cec780-5431-11ea-8e88-9d2170acb8e0.png)

I wonder whether it is expected or I have missed something? (The analysis of the underlying CDF can be found in my [notebook files](https://github.com/lukeluocn/shared-gists-and-notebooks/blob/master/cloudsuite-twitter-dataset/twitter-dataset-unscaled-plot.ipynb).) And what is the correct way to explain the dataset?

### A potential bug in generating random values

```c++
double cdf_to_lookup = (parRandomFunction(worker) % 100000000)/100000000.0;
```

The data-caching client uses `parRandomFunction` to generate look-up values, which should be within the range `[0, 1]` in general. However, `parRandomFunction` has a 50% chance to generate negative values because that `parRandomFunction` casts an `unsigned long` value into an `int` value.

```c++
int parRandomFunction(struct worker* worker){
    int rand_int = genrand(&(worker->myMT19937p));
    return rand_int;
}
```

```c++
unsigned long genrand(struct mt19937p* config);
```

I wonder whether it is expected or it is a bug?

**Comment by Xusine1131** [comment]
Hello,

Sorry for the late reply. 

To answer your first question, the dataset does define the frequency of *keys*, which should roughly follow the Zipfian distribution. There is no certain distribution for the *size* of the packet. 

Indeed, what you mentioned about negative values is a bug, and we fixed it in a more recent load generator.  We included [this patch](https://github.com/parsa-epfl/memcached-loadtester/pull/2) in the incoming release of CloudSuite 4.0. 

Best
