### ISSUE TITLE
graph and in-memory analytics error

### ISSUE THREAD

**Issue by hrmoradi** [parsa-epfl/cloudsuite#247]
Hi guys,

for running both of the graph and in-memory analytics benchmarks in multi-node mode I get "Failed to connect to master spark-master:7077", is there any way I can fix this problem? (I checked, master is working and lists 1 worker when checking web page on port 8080 correctly.)

**Comment by neo-apz** [comment]
Hi,

Can you please provide more information on how you are running these benchmarks? particularly, the specific commands you are running, and your setup.
This might be related to an issue with your network setup.

**Comment by hrmoradi** [comment]
Hi, 

Sure, 
$ sudo docker create --name data cloudsuite/movielens-dataset
$ sudo docker network create --driver bridge spark-net
$ sudo docker run -dP --net spark-net --hostname spark-master --name spark-master cloudsuite/spark master
$ sudo docker run -dP --net spark-net --volumes-from data --name spark-worker-01 cloudsuite/spark worker spark://spark-master:7077
$ sudo docker run --rm --net spark-net --volumes-from data cloudsuite/in-memory-analytics /data/ml-latest-small /data/myratings.csv --master spark://spark-master:7077

and then it gives me "Failed to connect to master spark-master:7077"

I connected an Ubuntu docker image to the same network to check the spark, it's running, you can see the worker is connected to master using the "master-ip:8080" and both  master and worker can be pinged.
Even the in-memory-analytics is connected to the network which can be inspected with: $ sudo docker inspect spark-net.

I found a clone of the CloudSuite which is working from another repository.

**Comment by neo-apz** [comment]
We will look into this and will get back to you ASAP.
In the meantime, could you please tell us what you meant by a different clone of CloudSuite?Where?

**Comment by alfiusss** [comment]
Hi, 

has this issue been solved? I also have same problem. Thanks

**Comment by neo-apz** [comment]
We have updated all the benchmarks and added new ones for our next release. Our `main` branch currently includes the pre-release version of CloudSuite 4 and the images are also available on DockerHub. We are in the last phase of testing the images across multiple platforms (including ARM and RISC-V). I'm closing this issue, feel free to reopen it or open a new issue if you have further questions.
