### ISSUE TITLE
How to pull docker image for aarch64?

### ISSUE THREAD

**Issue by oleotiger** [parsa-epfl/cloudsuite#255]
I want to run docker image on aarch64 Linux.
I have tried 
`docker pull cloudsuite/in-memory-analytics:3.0-aarch64`
`docker pull cloudsuite/benchmarks/in-memory-analytics:3.0-aarch64`
But both failed with the last returned "pull access denied. repository does not exist or may require docker login.

**Comment by oleotiger** [comment]
More info:
I tried pull docker image directly on aarch linux OS with 
`docker pull cloudsuite/in-memory-analytics`
But got run error:
`standard_init_linux.go:220: exec user process caused "exec format error"
libcontainer: container start initialization failed: standard_init_linux.go:220: exec user process caused "exec format error"`

**Comment by neo-apz** [comment]
We don't have ARM-based images yet.
We are currently working on a multi-platform version of CloudSuite (x65, arm64, and risc-v) which will be released soon as part of CloudSuite v4.
In the meantime, you can build the images yourself by using our dockerfiles.

We will let you know when we have the images ready so you can try them before we officially release them.

**Comment by oleotiger** [comment]
I'm trying build the aarch64 image with Dockerfile-aarch.
But here I get a problem. 
I hava tried:
- `FROM resin/aarch64-debian:jessie` changed to `FROM resin/aarch64-debian:stretch` as jessie EOL.
 and I have to change jdk7 to jdk8 as `stretch` has not jdk7.
The I got problem when building  `in-memory-analystics` . `typesafe-ivy-releases`  supports sbt 0.x version and `Maven Central`  supports 1.x version. 
I think the OS image `resin/aarch64-debian:stretch` is too old.

- Then I tried change to `FROM balenalib/aarch64-debian-node`
 But I got error when building `cloudsuite/java:openjdk7-aarch64`
I'm still debuging the error.

Any advice for building aarch64 image?
or which OS image should I choose?

**Comment by neo-apz** [comment]
Those are the old dockerfiles that are not supported anymore.
We are working on a new multi-platform version of CloudSuite, it is not released yet but you can give it a try.
Use the tag `4.0` for `in-memory-analytics` and `graph-analytics` to pull our new multi-platform images.

**Comment by oleotiger** [comment]
I have tried `in-memory-analytics` and it works~ with `cloudsuite/movielens-dataset` from `resin/aarch64-debian:jessie`.
There are some warnings. Any way, it did work. Thank you very much!

When will cloudsuite4.0 released? Any approximate time ?
In 4.0, will `cloudsuite/movielens-dataset` be update to a new OS image to remove those warnings?

**Comment by neo-apz** [comment]
The images are already available on DockerHub and you can pull them now, but they are not officially released.

**Comment by oleotiger** [comment]
Yeah，I have checked that most images under cloudsuite support arm64.
But the dataset image `cloudsuite/movielens-dataset` and `cloudsuite/twitter-dataset-graph` (only amd64 supported) have not been updated. The latest update is 2 years ago...
Will these two dataset updated as well with other images?

**Comment by neo-apz** [comment]
As I said earlier this is something we are currently working on. The two datasets are also pushed now and you can use them (tag `4.0`).

**Comment by neo-apz** [comment]
I'm closing this. Please reopen it if you have further questions.
