### ISSUE TITLE
Could somebody please explain in detail how cloudsuite/web-serving benchmark is working?

### ISSUE THREAD

**Issue by shez1461** [parsa-epfl/cloudsuite#258]
From what we already understand is that - 
The benchmark has four tiers: the web server, the database server, the memcached server, and the clients. The web server runs Elgg and it connects to the memcached server and the database server. The clients send requests to login to the social network. This benchmark mainly includes a social networking engine (Elgg) and a client implemented using the Faban workload generator.

After running the benchmark, the result in `summary.xml` shows about - `4.133` `ops/sec` with default workload generator being used - `7`
Looking at published results on - [Results](https://openbenchmarking.org/result/2004165-VE-20200417092,2004171-VE-20200418046,2004173-VE-20200418048,2004086-VE-20200408266)

Everybody in [openbenchmarking.org](openbenchmarking.org) are using this unit of measurement on web-serving and that more ops/sec is better. But it is not clear why?

(Apologies for naivest questions):
1) What is this benchmark actually trying to calculate?
2) Are operations per second the correct form of measurement for web-serving benchmark? if yes, how can one validate what it is? like for example if an activity ie; PostSelfWall or DoLogin is attempted at n times successfully & out of how many?
3) What is the default number of workload to use? and what does samples N=3 mean?
4) Using an ARM64/aarch64 for this benchmark is comparably very close to x86 arch in this case. Does that mean that all systems which have attempted this benchmark are almost equal in performing same number of operations per second but differentiated in micro milliseconds?
5) Are all sections detailed results in `/usr/src/faban/output/4/detail.xan` measured in milliseconds/seconds?

Thank you.

**Comment by pradeepk5** [comment]
>  What is this benchmark trying to calculate?

This is the benchmark for web front-end. Faban client generates a request (like login, posting, sending a message) to the web-server and generates statistics (summary.xml). The load can be changed by changing the load factor (default is 7), which increases the number of parallel running client threads.
For more detail refer the faban driver here {https://github.com/parsa-epfl/cloudsuite/blob/master/benchmarks/web-serving/faban_client/files/web20_benchmark/src/workload/driver/Web20Driver.java]

> Are operations per second the correct form of measurement for the web-serving benchmark? if yes, how can one validate what it is? like for example if an activity ie; PostSelfWall or DoLogin is attempted at n times successfully & out of how many?

When running the benchmark, it will show the flat mix of operation, which is the probability occurrence of each operation.s This is calculated from the request mix matrix in the faban client driver. Also, in summary.xml file, you can see the actual mix probability.

> What is the default number of workloads to use? and what does samples N=3 mean?

I am not sure what do you mean by N=3. The load factor (default 7) denotes the number of client thread/faban driver thread to run. Larger the factor means the heavy load. You have to choose the load factor according to your system setting, also make sure your latency constraints are not violated.

> Using an ARM64/aarch64 for this benchmark is comparably very close to x86 arch in this case. Does that mean that all systems which have attempted this benchmark are almost equal in performing the same number of operations per second but differentiated in micro milliseconds?

We are not aware of your experiment environment, so we cannot give a clear answer. Generally, not all systems will achieve the same throughput. We have to change the load and find the maximum load under which the server can sustain.

> Are all sections detailed results in /usr/src/faban/output/4/detail.xan measured in milliseconds/seconds?

Millisecond is the default unit. Also, you can see it's mentioned in XML file
