### ISSUE TITLE
Multi-platform support for the Spark datasets

### ISSUE THREAD

**Issue by neo-apz** [parsa-epfl/cloudsuite#259]
The two dataset images, `movielens-dataset` and `twitter-dataset-graph`, used by Spark workloads are not available on other platforms and missing from #244. 
@alok123t @komal1204

**Comment by alok123t** [comment]
@neo-apz for the `twitter-dataset-graph` the link to download doesn't work. Do you happen to know any alternate link for download?
Or we can `docker pull cloudsuite/twitter-dataset-graph` and host the dataset and download from there

**Comment by neo-apz** [comment]
It seems it has been removed (most of the twitter datasets have been removed in the past couple of years). I think we should get the files from the old image.

**Comment by VamshiMuthineni** [comment]
can the twitter dataset be hosted on cloudsuite server?

**Comment by neo-apz** [comment]
Yes we can serve it along with the other files.
Can you create a zip file containing the dataset? we will then host it on our server.

**Comment by VamshiMuthineni** [comment]
Please download the zip from [https://drive.google.com/file/d/1gj-_MLINUDEqLIAysykVFfIPvfx3C6mb/view?usp=sharing](url).

**Comment by neo-apz** [comment]
Here is the URL: https://cloudsuite.ch/download/graph_analytics/twitter_dataset.zip

**Comment by VamshiMuthineni** [comment]
updated.
