### ISSUE TITLE
Which branch is corresponding to tag 4.0?

### ISSUE THREAD

**Issue by oleotiger** [parsa-epfl/cloudsuite#262]
In a closed issue I got the message that Cloudsuite with tag 4.0 is being developped and will be released soon.
Cloudsuite 4.0 supports for multiple platform such as X86, aarch64.

Which branch of the github repo is corresponding to cloudsuite 4.0?

**Comment by neo-apz** [comment]
The `dev` branch has the latest modifications and additions. It is still work in progress and not fully supported yet. You can build the images and try to run them on your own.

**Comment by neo-apz** [comment]
Our `main` branch currently includes the pre-release version of CloudSuite 4 and the images are also available on DockerHub. We are in the last phase of testing the images across multiple platforms (including ARM and RISC-V). I'm closing this issue, feel free to reopen it or open a new issue if you have further questions.
