### ISSUE TITLE
web serving kubernetes deployment

### ISSUE THREAD

**Issue by rajibhossen** [parsa-epfl/cloudsuite#272]
I'm looking for Kubernetes manifests (YAML) file to deploy web serving in the Kubernetes cluster. I can write YAML files but there are some issues. For example, docker image "web_server" invokes a shell script called "bootstrap.sh", "bootstrap.sh" also takes an IP as a command-line argument. I'm not sure how can I work around these in Kubernetes. It would be great if we can include Kubernetes configuration in this repository. I'm available to work on this issue.

**Comment by neo-apz** [comment]
We have updated all the benchmarks and added new ones for our next release.

Our `main` branch currently includes the pre-release version of CloudSuite 4 and the images are also available on DockerHub. We are in the last phase of testing the images across multiple platforms (including ARM and RISC-V).

Regarding the Kubernetes deployment, we are currently not planning to include that as part of our release. But we would be happy to have that if you have the time to work on it. Please create a pull request with the required changes and we will consider your contribution. Thanks.

 I'm closing this issue, feel free to reopen it or open a new issue if your question still persists or you have further questions.
