### ISSUE TITLE
About Web-Search benchmarks query

### ISSUE THREAD

**Issue by liyaogang97** [parsa-epfl/cloudsuite#276]
In the client container, I checked the creation logic of the request query, and there was a file named terms_ordered. I don't understand what the first number in each record means. Can someone answer me please? Thank you very much.

**Comment by Xusine1131** [comment]
Hello,

These files are actually the data set. They define the frequency weight of a specific key word, which is combined to generate a search key word query. You can find the code for the detailed usage in [Random.java](https://github.com/parsa-epfl/cloudsuite/blob/main/benchmarks/web-search/client/files/search/distributions/Zipfian.java) or [Zipfian.java](https://github.com/parsa-epfl/cloudsuite/blob/main/benchmarks/web-search/client/files/search/distributions/Zipfian.java).

Best
