### ISSUE TITLE
Hadoop Server Should Listen All interface and All IP range

### ISSUE THREAD

**Issue by Xusine1131** [parsa-epfl/cloudsuite#317]
Now it seems that Hadoop master only listened on docker internal network and the listening address is "127.0.1.1". We have to:
1. Expose ports so that all other interfaces could have permission to accept the connection. 
2. Change listening address to 0.0.0.0 so that it could accept the slaves with arbitrary address segments.

**Comment by Xusine1131** [comment]
Reference: https://github.com/big-data-europe/docker-hadoop/blob/master/base/entrypoint.sh

**Comment by chapaith** [comment]
Hi there, Can I work on this issue?

**Comment by Xusine1131** [comment]
> Hi there, Can I work on this issue?

Hello,
You are welcome to contribute your code to our project by making a pull request. We will review and test your code, and then we merge it into the main branch.

Best,

**Comment by chapaith** [comment]
> > Hi there, Can I work on this issue?
> 
> Hello, You are welcome to contribute your code to our project by making a pull request. We will review and test your code, and then we merge it into the main branch.
> 
> Best,

Thank You so much Sir to providing me this as a opportunity.

**Comment by chapaith** [comment]
I hope this is the motive to change the listening IP address to 0.0.0.0. Please correct, me if I'm wrong, 

The address 0.0.0.0 is a non-routable meta-address used to designate an invalid, unknown or non-applicable target. It may also be used when the client is offline. And the context of servers, 0.0.0.0 can mean "all IPv4 addresses on the local machine". If a host has two IP addresses, 192.168.1.1 and 10.1.2.1, and a server running on the host is configured to listen on 0.0.0.0, it will be reachable at both of those IP addresses.???

And finally, I have to change the listening address to 0.0.0.0, what is this issue all about??

**Comment by Xusine1131** [comment]
This PR will be addressed in the incoming PR #416 .
