### ISSUE TITLE
502 Bad Gateway on Web-Serving

### ISSUE THREAD

**Issue by aansaarii** [parsa-epfl/cloudsuite#322]
I cannot successfully run the web-serving benchmark on x86. 
I follow this process:

```
docker pull cloudsuitetest/web-serving:db_server
docker run -dt --net=host --name=database_server cloudsuitetest/web-serving:db_server X.X.X.X
```

that the last one is my ip obtained by `hostname -I | awk '{print $1}'`

```
docker pull cloudsuitetest/web-serving:memcached_server
docker run -dt --net=host --name=memcache_server cloudsuitetest/web-serving:memcached_server
docker pull cloudsuitetest/web-serving:web_server
docker run -dt --net=host --name=web_server cloudsuitetest/web-serving:web_server /etc/bootstrap.sh 127.0.0.1 127.0.0.1 ${MAX_PM_CHILDREN}
docker pull cloudsuitetest/web-serving:faban_client
docker run --net=host --name=faban_client cloudsuitetest/web-serving:faban_client X.X.X.X ${LOAD_SCALE}
```

that is the same ip given above

The output:
```
Could not perform HTTP 200 GET from: X.X.X.X:8080
```

**Comment by Hnefi** [comment]
I managed to reproduce this first time. Can you please confirm that in your web server's container log, you see something like the following?

> [02-Aug-2021 17:56:23] WARNING: [pool www] child 361 exited on signal 7 (SIGBUS - core dumped) after 4.290952 seconds from start
> [02-Aug-2021 17:56:23] NOTICE: [pool www] child 363 started
> [02-Aug-2021 17:56:25] WARNING: [pool www] child 362 exited on signal 7 (SIGBUS - core dumped) after 4.284987 seconds from start
> [02-Aug-2021 17:56:25] NOTICE: [pool www] child 364 started
> [02-Aug-2021 17:56:27] WARNING: [pool www] child 363 exited on signal 7 (SIGBUS - core dumped) after 4.285613 seconds from start
> [02-Aug-2021 17:56:27] NOTICE: [pool www] child 365 started

Seems like the problem is that all the PHP CGI processes just crash (OOM?) immediately after forking.

**Comment by aansaarii** [comment]
> I managed to reproduce this first time. Can you please confirm that in your web server's container log, you see something like the following?
> 
> > [02-Aug-2021 17:56:23] WARNING: [pool www] child 361 exited on signal 7 (SIGBUS - core dumped) after 4.290952 seconds from start
> > [02-Aug-2021 17:56:23] NOTICE: [pool www] child 363 started
> > [02-Aug-2021 17:56:25] WARNING: [pool www] child 362 exited on signal 7 (SIGBUS - core dumped) after 4.284987 seconds from start
> > [02-Aug-2021 17:56:25] NOTICE: [pool www] child 364 started
> > [02-Aug-2021 17:56:27] WARNING: [pool www] child 363 exited on signal 7 (SIGBUS - core dumped) after 4.285613 seconds from start
> > [02-Aug-2021 17:56:27] NOTICE: [pool www] child 365 started
> 
> Seems like the problem is that all the PHP CGI processes just crash (OOM?) immediately after forking.

Which file's content is this?

**Comment by aansaarii** [comment]
It seems that the problem's reason is the `db_server `container. When I replace the `db_server` from the one on the `master `branch, the benchmark runs successfully. But when I use the one on the `dev `branch, the benchmark fails as the `web-server` returns only 502 Bad Gateway error.
