### ISSUE TITLE
Long build latency for HHVM

### ISSUE THREAD

**Issue by neo-apz** [parsa-epfl/cloudsuite#341]
The HHVM image takes a long time to be built because it's trying to build everything from sources. We should take a look at it and see whether it can be modified to use some pre-built packages to speed up the build process.

**Comment by Xusine1131** [comment]
HHVM indeed have binary release for debian, see here:
https://dl.hhvm.com/debian/pool/main/h/hhvm/
However, the problem is that the version of hhvm we use is 3.30, which is not officially provided for Debian buster. In this case, we either downgrade Debian or upgrade hhvm to 4.

**Comment by Xusine1131** [comment]
We decide to remove this workload from the incoming release.
