### ISSUE TITLE
Web Serving benchmark db_server question 

### ISSUE THREAD

**Issue by ryuxin** [parsa-epfl/cloudsuite#350]
There is a file named `my.cnf` in the path `benchmarks/web-serving/db_server/files/`. 
How is that file used when building the `db_server` docker image? I do not find any place to use that file.

**Comment by ryuxin** [comment]
similar question to `generate_users.sh` file. 
I do not know how to use it

**Comment by Xusine1131** [comment]
Sorry for the late reply.
1. `my.cnf` is needed in the early version of the database server, to specify the listen address. However, now this part is replaced by this line: https://github.com/parsa-epfl/cloudsuite/blob/main/commons/mysql/mariadb-10.3/Dockerfile#L15
2. `generate_users.sh` is used to generate the database initialization file `elgg_db.dump`. ELGG cannot directly runs over an empty database. 

Feel free to reopen if you have further questions.


Best,
