### ISSUE TITLE
Is it possible to limit max threads in Solr server side?

### ISSUE THREAD

**Issue by hao-lee** [parsa-epfl/cloudsuite#354]

**Comment by Xusine1131** [comment]
Hello,

Not sure if you have figured out how to do it, but a possible solution is to reduce the cores assigned to the server container, and the number of threads should be reduced accordingly.
You can specify cores assigned to the container by using option `--cpuset-cpus` when running the container.

Best,

**Comment by Xusine1131** [comment]
Hello,

I assume you figure out how to solve this problem, and I will close this issue at present. Feel free to open it again if you still have the problem,

Best,
