### ISSUE TITLE
Media-streaming on RISC-V

### ISSUE THREAD

**Issue by aansaarii** [parsa-epfl/cloudsuite#364]
The dataset container cannot be built for RISC-V architecture from the source. 
Consider updating: libavcodec58 to libavcodec59, libavfilter7 to libavfilter8, libavdevice58 to libavdevice59, and libavformat58 to libavformat59.

**Comment by Xusine1131** [comment]
Once we move to Ubuntu 22.04 base image, we don't need to specially handle the RISC-V case, and these packages (libavformat59. etc.) are actually missing from Ubuntu 22.04.
