### ISSUE TITLE
TLS on media streaming

### ISSUE THREAD

**Issue by aansaarii** [parsa-epfl/cloudsuite#380]
The client crashes after some time running the benchmark with encryption mode. It breaks at this [line](https://github.com/parsa-epfl/cloudsuite/blob/fix_streaming_server/benchmarks/media-streaming/client/files/videoperf/core.c#L1000).
It prints: `httperf: failed to connect to SSL server (err=-1, reason=5)`

**Comment by Xusine1131** [comment]
It is because the server is overloaded.
