### ISSUE TITLE
Memory Size on Data-Caching

### ISSUE THREAD

**Issue by aansaarii** [parsa-epfl/cloudsuite#387]
The commands in the data-caching benchmark instruct the user to generate a ~10 GB dataset. But it gives 4 GB memory to the Memcached server. As a result, the whole dataset is not in the memory and causes page faults. We have to update the doc to mention this and ask the users to tune the memory usage based on their preference. 
Moreover, the 10ms tail latency is very large. Consider a 1ms tail latency for this benchmark.

**Comment by UlisesLuzius** [comment]
#399
