### ISSUE TITLE
Media Streaming Multi-node 

### ISSUE THREAD

**Issue by Bingseolhwa** [parsa-epfl/cloudsuite#429]
Hello.

Data Analytics, In-memory Analytics and Data serving Benchmark Application  have a multi-node setup in the docs. 
I was wondering if media streaming is also a multi-node setup. and If this is possible, I'd love to see an example of how to do it.

**Comment by Xusine1131** [comment]
Hello,

Media streaming is a workload based on Nginx, so if you want to run it with multiple nodes, you may need a HTTP load balancer like another layer of Nginx, or some standard API gateway (e.g., [Kong](https://github.com/Kong/kong)). At present, we don't have a plan for it.

Best,

**Comment by Bingseolhwa** [comment]
> Hello,
> 
> Media streaming is a workload based on Nginx, so if you want to run it with multiple nodes, you may need a HTTP load balancer like another layer of Nginx, or some standard API gateway (e.g., [Kong](https://github.com/Kong/kong)). At present, we don't have a plan for it.
> 
> Best,

Thank you reply.
You're saying that media streaming doesn't benchmark clusters yet?

**Comment by Xusine1131** [comment]
You are right. Currently you cannot run single Media Streaming instance to benchmark a cluster.
