### ISSUE TITLE
Support for NoSQL systems

### ISSUE THREAD

**Issue by mscsf15m027** [parsa-epfl/cloudsuite#81]
Cloudsuite supports which NoSQL system? Please tell me the names of those systems.

**Comment by ustiugov** [comment]
Hi!

Thank you for your interest in CloudSuite. 

You could consider Data Serving (Cassandra). For more information, please refer to our website cloudsuite.ch

Regards,
Dmitrii

**Comment by mscsf15m027** [comment]
I figured out that
Hadoop
Spark
Cassendra
Memcached
only these systems supported by cloudsuite. Is there anyone else?
