### ISSUE TITLE
Support for NoSQL systems

### ISSUE THREAD

**Issue by mscsf15m027** [parsa-epfl/cloudsuite#83]
According to my search I figure out that cloudsuite only support cassendra,memcached,Spark. Is there anyone else for which cloudsuite benchmark can be used? I have visited your official website as well and find these three systems benchmarking with different workloads. Actually i want to know about the all those NoSQL systems which are supported by cloudsuite. Kindly help me.

**Comment by neo-apz** [comment]
CloudSuite is a benchmark suite for cloud services, and it covers a broad range of application categories commonly found in today’s datacenters. Currently, it includes 8 benchmarks:

- Data Analytics
- Data Caching
- Data Serving
- Graph Analytics
- In-memory Analytics
- Media Streaming
- Web Search
- Web Serving

Technically, only one these benchmarks uses a NoSQL system in its backend, which is Data Serving that uses Cassandra. For more information please take a look at [this page](http://cloudsuite.ch///pages/benchmarks/dataserving/).
