### ISSUE TITLE
Error in faban client when number number of clients are increased more than 300, I am running the web serving benchmark!

### ISSUE THREAD

**Issue by kartikjoshi07** [parsa-epfl/cloudsuite#84]
```
Apr 15, 2017 9:50:45 AM com.sun.faban.driver.engine.AgentThread logError
     [java] WARNING: ElggDriverAgent[0].112.addFriend: Server returned HTTP response code: 502 for URL: http://10.6.9.155:8050/action/friends/add?friend=362&__elgg_ts=1492249412&__elgg_token=f46722e9c46ebaed9b2f4495933a031b
     [java] java.io.IOException: Server returned HTTP response code: 502 for URL: http://10.6.9.155:8050/action/friends/add?friend=362&__elgg_ts=1492249412&__elgg_token=f46722e9c46ebaed9b2f4495933a031b
```

These kinds of error occur and throughput degrades drastically.
Sometimes there is  HTTP response code: 503 and sometimes  HTTP response code: 504

Is it due to server saturation/overload?

**Comment by nooshin-mirzadeh** [comment]
Dear kartikjoshi07, 

Thanks for asking this question. 
It means that your server cannot handle this number of users. You should find the reason based on the characteristics of the machine that you are running the web serving on. Please check the amount of memory that you have and also check the CPU usage.
