### ISSUE TITLE
Different benchmarks use different versions of spark (and hadoop)

### ISSUE THREAD

**Issue by sangnie** [parsa-epfl/cloudsuite#89]
benchmarks/spark-base/spark-base uses SPARK_VERSION 1.5.1 and HADOOP_VERSiON 2.6 but the commons folder contains HADOOP 2.7.3 and SPARK 1.5.1 as well as 2.1.0. Hadoop is used in data-analytics and spark in in-memory-analytics and graph analytics. I do not know if they will create compatibility issues elsewhere.

**Comment by neo-apz** [comment]
`spark-base` images will be removed soon, and we will only use the common spark image.
