### ISSUE TITLE
'Data-caching' configuration to burden memory

### ISSUE THREAD

**Issue by yunjeongmun** [parsa-epfl/cloudsuite#92]
I want to analyze the memory performance (Bandwidth, memory usage..) of the CloudSuite3.0
Especially I run the 'data-caching' 
Experiment environment is written below
              - 2 Socket, 32 cores (16cores/socket)
              - Memory:  2133MHz, 32GB  * 16
              - Network throughput: 1gb/s   
              - I don't use the 'docker'
                    - 'data-caching':  memcached-1.4.24 for memcached server
                                                twitter_dataset and memcached_client offered by CloudSuite for clients
             
In case of 'data-caching':
 In this experiment, I expected that the 'data-caching' uses memory bandwidth pretty much, but it doesn't and it is bounded by the CPU.  I'm confused that the below configuration is correct. 

 Server network is too slow to test the 'data-caching', so I run memcached server and client in the physically one server, and make them use different socket respectively. (16cores/socket)
             - 4 server processes with 16 threads for each process  
             - 40GB server main memory size 
             - 100 client with 16 client threads for each server process (total 100*4 = 400clients)
             - 10GB twitter data set (Scaling factor of 30)
In this case, average memory bandwidth utilization is about 6GB/s and 10GB/s for server and client,
                    average memory usage is 5GB and 2GB for each server process and client process,
                    (We measured resident set size as a memory usage)
                    and the CPU utilization is 1560% and 1200% for server processes and client processes.

I want to know that above configuration is reasonable and is there any other configuration to burden memory.

**Comment by neo-apz** [comment]
I'm closing this for now.
Feel free to reopen it if you have any further questions.
