### ISSUE TITLE
in-memory-analytics executor memory size

### ISSUE THREAD

**Issue by yunjeongmun** [parsa-epfl/cloudsuite#96]
I run in-memory-analytics without docker. Experiment environment is written below
- spark-2.1.0-bin-hadoop2.4
- movielens-als data set
- Multi-node deployment (1 master, 1 worker, 1 executor)

I complete the execution of this with 'ml-latest-small' input set. And I want to run with more bigger input set 'ml-latest'. But if I run it with  --driver-memory 1g --executor-memory 1g option as described on the tutorial page, I got an error message :  java.lang.OutOfMemoryError: Java heap space

I checked that executor memory is set to 2GB in the SparkConf() MovieLensALS.scala. 
 .set("spark.executor.memory", "2g") 
I want to remove that line of the code and set the 'executor-memory' size explicitly in run-time.

I'm struggling with the re-build MovieLensALS.scala..
How can I build it ?
And.. do you have any recommendation for proper executor memory size to run ml-latest input ?

Thanks

**Comment by ZiluTian** [comment]
Hello, is the question still relevant? Or have you found a solution?

**Comment by yunjeongmun** [comment]
Actually, I haven't found the solution yet.
I just increase the number of workers and each worker have used l-latest-small'. It works fine. 
Is there any way to increase executor memory size without any modification of source code?

**Comment by ZiluTian** [comment]
Hi, thanks for your response. Currently there is no work around to specify the executor memory size from the command line. The size is hard coded in SparkConf() to ensure the functionality of the program. There is an on-going effort related to an issue in cloudsuite/spark, which is needed for generating a docker image for this benchmark. Once it is fixed, you can clone the source codes for in-memory-analytics and generate a new docker image with your hacked codes, following the instruction here
 
https://docs.docker.com/engine/reference/commandline/image_build/  

If you prefer the bare metal approach, you can find some useful information about running scala here: 
https://www.tutorialspoint.com/scala/scala_quick_guide.htm

Hope it helps.
