### ISSUE TITLE
CloudSuite benchmarks not working in swarm mode

### ISSUE THREAD

**Issue by ebarlaskar** [parsa-epfl/cloudsuite#97]
Hi all,

This issue is related to the issue #87. 

I was trying to run media streaming benchmark from cloudsuite in swarm mode by following the instructions given in http://cloudsuite.ch//2015/12/20/swarm/. I was expecting that with an overlay network in swarm mode I can make containers from different nodes communicate. But every time I use a locally built image or if I use the images from a private repository from my docker hub account, swarm fails to start the containers. I even tried to pull the images from cloudsuite; still it fails.  Below are the steps that I have followed so far:

I have run all the commands in swarm master and pulled the images in swarm worker node 1, node 2 and node 3 as below:

****To build dataset****

**swarm_node1:** 
sudo docker pull cloudsuite/media-streaming:dataset

**Swarm_master:** 
$ sudo docker service create --name streaming_dataset --network swarm-network  --constraint "node.id==ffx5v6f1ddnxtb1g8434q27dn" -d cloudsuite/media-streaming:dataset
33612kongezcbodk1o7n4lv8b

$ sudo docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                                PORTS
33612kongezc        streaming_dataset   replicated          0/1                 cloudsuite/media-streaming:dataset  

Although the container is created, it fails to start in the worker node 1 or any other worker nodes and I get the following information:

$ sudo docker service ps streaming_dataset --no-trunc
ID                          NAME                      IMAGE                                                                                                        NODE                DESIRED STATE       CURRENT STATE                 ERROR               PORTS
rpl6yvtqy7qdcx3pw7pdbf5oz   streaming_dataset.1       cloudsuite/media-streaming:dataset@sha256:cd3f09ae1f75ccb91608ec3ac6cf9cba1cf63f83bee4e5c92992bd8d5b144879   swarm1              Running             Preparing 5 seconds ago                           
w456i5k8wotxrzds15tffiiji    \_ streaming_dataset.1   cloudsuite/media-streaming:dataset@sha256:cd3f09ae1f75ccb91608ec3ac6cf9cba1cf63f83bee4e5c92992bd8d5b144879   swarm1              Shutdown            Complete 5 seconds ago                            
j5wh0m90el0uoay3rf31xt0bs    \_ streaming_dataset.1   cloudsuite/media-streaming:dataset@sha256:cd3f09ae1f75ccb91608ec3ac6cf9cba1cf63f83bee4e5c92992bd8d5b144879   swarm1              Shutdown            Complete about a minute ago                       
sreqi2kbovb5wu3cq4t0dme3b    \_ streaming_dataset.1   cloudsuite/media-streaming:dataset@sha256:cd3f09ae1f75ccb91608ec3ac6cf9cba1cf63f83bee4e5c92992bd8d5b144879   swarm1              Shutdown            Complete 3 minutes ago 

****To run the server****

Next, I tried to run the streaming server and it was working fine.

**Swarm Master:**
$ sudo docker service create --name streaming_server --network swarm-network --mount type=volume,source=streaming_dataset,destination=/streaming_dataset --constraint "node.id==ffx5v6f1ddnxtb1g8434q27dn" cloudsuite/media-streaming:server

ic3h22efitlc0khdl3dv6as7p
Since --detach=false was not specified, tasks will be created in the background.
In a future release, --detach=false will become the default.

$ sudo docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                                PORTS
ic3h22efitlc        streaming_server    replicated          1/1                 cloudsuite/media-streaming:server    
ijov1x016sf5        streaming_dataset   replicated          0/1                 cloudsuite/media-streaming:dataset   

****To run the client****

As the server was running in swarm node 1 so I tried to run the client in swarm node 3:

**Swarm Master:**
$ sudo docker service create -t --name=streaming_client --mount type=volume,source=streaming_dataset,destination=/path/to/output:/output --constraint "node.id==55cipngnlvcp1z7le0vnhgfx2" --network swarm-network cloudsuite/media-streaming:client streaming_server

viiu9vfcn99da1nifri8cymdq
Since --detach=false was not specified, tasks will be created in the background.
In a future release, --detach=false will become the default.

Although the client is deployed in swarm node 3 but it fails after few seconds:

$ sudo docker service ps streaming_client 
ID                  NAME                     IMAGE                               NODE                DESIRED STATE       CURRENT STATE           ERROR                       PORTS
9yvb1kl81y3v        streaming_client.1       cloudsuite/media-streaming:client   swarm3              Ready               Ready 3 seconds ago                                 
dy9hte7l3xbw         \_ streaming_client.1   cloudsuite/media-streaming:client   swarm3              Shutdown            Failed 4 seconds ago    "task: non-zero exit (1)"   
ubh8u9qy60cy         \_ streaming_client.1   cloudsuite/media-streaming:client   swarm3              Shutdown            Failed 11 seconds ago   "task: non-zero exit (1)"   
jnhd85bpbd0k         \_ streaming_client.1   cloudsuite/media-streaming:client   swarm3              Shutdown            Failed 18 seconds ago   "task: non-zero exit (1)"   
zo1nhf69zppm         \_ streaming_client.1   cloudsuite/media-streaming:client   swarm3              Shutdown            Failed 24 seconds ago   "task: non-zero exit (1)"  

Am I missing something in the process of deploying the media streaming client and dataset in swarm mode? I would appreciate any sort of assistance in this regard.

P.S: other benchmarks(GraphAnalytics, DataCaching) from Cloudsuite are also failing the same way in swarm mode.

Many thanks.
Esha

**Comment by msahihi** [comment]
@ebarlaskar  I had the same issue but it goes back to MTU size of the overlay network. 
did you check the MTU size of the container ? its value should be less than actual MTU size of ethernet on the host.
If you are using OpenStack to create your VM and containers inside it, you may face this issue.
In this case, when you create overlay network change it's MTU by using `com.docker.network.driver.mtu=1450`

to create the network in swarm use below code.
`sudo docker -H:4000 network create --opt com.docker.network.driver.mtu=1450 --driver overlay NETWORK_NAME`

**Comment by ustiugov** [comment]
Hey Guys, please reopen if relevant.
