### ISSUE TITLE
Hello, i have some problem... help me....

### ISSUE THREAD

**Issue by dldldlfma** [parsa-epfl/cloudsuite#98]
Hi~! 

I want to test my cloud.

So, I try to CloudSuite. 

But Data_Analytics isn't working.....

Data_Analytics benchmark show this message.

Mahout: seqwiki
MAHOUT_LOCAL is not set; adding HADOOP_CONF_DIR to classpath.
Running on hadoop, using /opt/hadoop-2.7.3/bin/hadoop and HADOOP_CONF_DIR=/opt/hadoop-2.7.3/etc/hadoop
MAHOUT-JOB: /opt/mahout-0.12.2/mahout-examples-0.12.2-job.jar
17/08/07 12:45:51 INFO WikipediaToSequenceFile: Input: /user/root/wiki Out: /user/root/wiki-seq Categories: /root/categories All Files: false
17/08/07 12:45:52 INFO RMProxy: Connecting to ResourceManager at master/10.0.9.2:8032
17/08/07 12:45:53 WARN JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
17/08/07 12:45:54 INFO FileInputFormat: Total input paths to process : 1
17/08/07 12:45:54 INFO JobSubmitter: number of splits:5
17/08/07 12:45:55 INFO JobSubmitter: Submitting tokens for job: job_1502109896912_0001
17/08/07 12:45:55 INFO YarnClientImpl: Submitted application application_1502109896912_0001
17/08/07 12:45:55 INFO Job: The url to track the job: http://master:8088/proxy/application_1502109896912_0001/
17/08/07 12:45:55 INFO Job: Running job: job_1502109896912_0001

And i can't see next step.... 

I already complete this step in other computer.

How can i solve this problem?

I want to see next step.... :(

Help me~!~!

Thank you!!

**Comment by HKassir72** [comment]
Hello,
Thanks for using cloudsuite.
One reason why the benchmark is not doing any progress is that the master is not receiving any packets from the slaves.
To check, we can use yarn's resource manager webUI.
To do that, first publish the master's webUI port:
"docker run -d --net hadoop-net --name master --hostname master cloudsuite/data-analytics master"
Then run the slaves with the same command.
After launching the benchmark script ("docker exec master benchmark"), open, in your browser "http://localhost:8088/". You can see the status of the application here.

For more information about the webUI you check: http://hadooptutorial.info/yarn-web-ui/

You might need to publish other ports from the master node. A full list of yarn list can be found here: https://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.6.2/bk_reference/content/yarn-ports.html

Please let us know if this helps.
Regards,
Hussein

**Comment by hrmoradi** [comment]
> Hi~!
> 
> I want to test my cloud.
> 
> So, I try to CloudSuite.
> 
> But Data_Analytics isn't working.....
> 
> Data_Analytics benchmark show this message.
> 
> Mahout: seqwiki
> MAHOUT_LOCAL is not set; adding HADOOP_CONF_DIR to classpath.
> Running on hadoop, using /opt/hadoop-2.7.3/bin/hadoop and HADOOP_CONF_DIR=/opt/hadoop-2.7.3/etc/hadoop
> MAHOUT-JOB: /opt/mahout-0.12.2/mahout-examples-0.12.2-job.jar
> 17/08/07 12:45:51 INFO WikipediaToSequenceFile: Input: /user/root/wiki Out: /user/root/wiki-seq Categories: /root/categories All Files: false
> 17/08/07 12:45:52 INFO RMProxy: Connecting to ResourceManager at master/10.0.9.2:8032
> 17/08/07 12:45:53 WARN JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
> 17/08/07 12:45:54 INFO FileInputFormat: Total input paths to process : 1
> 17/08/07 12:45:54 INFO JobSubmitter: number of splits:5
> 17/08/07 12:45:55 INFO JobSubmitter: Submitting tokens for job: job_1502109896912_0001
> 17/08/07 12:45:55 INFO YarnClientImpl: Submitted application application_1502109896912_0001
> 17/08/07 12:45:55 INFO Job: The url to track the job: http://master:8088/proxy/application_1502109896912_0001/
> 17/08/07 12:45:55 INFO Job: Running job: job_1502109896912_0001
> 
> And i can't see next step....
> 
> I already complete this step in other computer.
> 
> How can i solve this problem?
> 
> I want to see next step.... :(
> 
> Help me~!~!
> 
> Thank you!!

Hi,
Did you find any solution?
thanks
